/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.orpik.ui;

import java.awt.Component;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.orpik.core.Product;
import org.orpik.core.Tanks;
import org.orpik.helper.HelperDips;

/**
 *
 * @author chemweno
 */
public class Dips extends javax.swing.JPanel {

    private DefaultTableModel tbmDips = new DefaultTableModel();
    private HelperDips helperDips = new HelperDips();
    private Product product = new Product();
    private ProductsUi productsUi = new ProductsUi();
    private Tanks tanks = new Tanks();

    /**
     * Creates new form Dips
     */
    public Dips() {
        initComponents();
        //Prepare table
        helperDips.prepareTable(tbmDips, tblDips, "Date", "Product", "Tank", "Opening Dips", "Closing Dips", "Product Sold (Dip Sale)");
        //Populate tanks in combo box
        tanks.poulateTanks(cboDipsTanks);
        tanks.poulateTanks(cboDipsAddDipsTank); 
        //Populate products in combo box
        productsUi.populateProducts(cboDipsAddDipsProduct);
    }

    /*
     tblDips = new javax.swing.JTable(tbmDips) {
     public Component prepareRenderer(TableCellRenderer renderer, int row, int
     col) { Component comp = super.prepareRenderer(renderer, row, col); 
     if(row%2==0) {
     //Set even numbered rows to yellow 238-232-170
     comp.setBackground(new java.awt.Color(224, 224, 255)); 
     } else {
     //Set odd numbered rows to purple 147-112-219
     comp.setBackground(new java.awt.Color(255, 255, 255)); 
     } return comp; 
     }
     
     public boolean isCellEditable(int row, int column) {
     //Disable editing on all rows of the table
     return false;	  
     } 
     };	
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateDips() {
        try {
            //Remove all rows in table
            tbmDips.setRowCount(0);
            Date dateFrom = dteDipsFrom.getDate() != null ? dteDipsFrom.getDate() : DateFormat.getDateInstance().parse("Jan 01, 1980");
            Date dateTo = dteDipsTo.getDate() != null ? dteDipsTo.getDate() : DateFormat.getDateInstance().parse("Nov 01, 2120");
            helperDips.populateDipsOnTable(tbmDips, tblDips, product.getProductIds(chkDipsDiesel, chkDipsPetrolRegular,
                    chkDipsPetrolSuper, chkParaffin), tanks.getTankIds(), dateFrom, dateTo);
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }

    private String getProductIds() {
        String productIds = "";
        try {
        } catch (Exception exception) {
            exception.printStackTrace();
        }
        return productIds;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgDips = new javax.swing.ButtonGroup();
        dlgDipsAddDips = new javax.swing.JDialog();
        pnlAddDipsMain = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboDipsAddDipsProduct = new javax.swing.JComboBox();
        txtDipsAddDipsPreviousClosingDip = new javax.swing.JTextField();
        dteDipsAddDipsDate = new com.toedter.calendar.JDateChooser();
        btnDipsCancel = new javax.swing.JButton();
        btnDipsAddDips = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cboDipsAddDipsTank = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtDipsAddDipsOpeningDip = new javax.swing.JTextField();
        pnlDipsTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboDipsTanks = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        dteDipsFrom = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        dteDipsTo = new com.toedter.calendar.JDateChooser();
        pnlDipsTopTitle = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rbtDipsAll = new javax.swing.JRadioButton();
        btnDipsView = new javax.swing.JButton();
        chkDipsPetrolRegular = new javax.swing.JCheckBox();
        chkDipsPetrolSuper = new javax.swing.JCheckBox();
        chkDipsDiesel = new javax.swing.JCheckBox();
        chkParaffin = new javax.swing.JCheckBox();
        pnlDipsMiddle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDips = new javax.swing.JTable();
        pnlDipsBottom = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        dlgDipsAddDips.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgDipsAddDips.setMinimumSize(new java.awt.Dimension(400, 330));
        dlgDipsAddDips.setPreferredSize(new java.awt.Dimension(392, 330));
        dlgDipsAddDips.setResizable(false);

        pnlAddDipsMain.setMinimumSize(new java.awt.Dimension(392, 330));
        pnlAddDipsMain.setPreferredSize(new java.awt.Dimension(392, 330));

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel6.setText("Add Dips");

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel7.setText("Date");

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel8.setText("Previous Closing Dip");

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel9.setText("Product");

        cboDipsAddDipsProduct.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        txtDipsAddDipsPreviousClosingDip.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        dteDipsAddDipsDate.setDateFormatString("dd-MM-yyyy");
        dteDipsAddDipsDate.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        btnDipsCancel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnDipsCancel.setMnemonic('C');
        btnDipsCancel.setText("Cancel");

        btnDipsAddDips.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnDipsAddDips.setMnemonic('A');
        btnDipsAddDips.setText("Add Dips");

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel10.setText("Tank");

        cboDipsAddDipsTank.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel11.setText("Opening Dip");

        txtDipsAddDipsOpeningDip.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlAddDipsMainLayout = new javax.swing.GroupLayout(pnlAddDipsMain);
        pnlAddDipsMain.setLayout(pnlAddDipsMainLayout);
        pnlAddDipsMainLayout.setHorizontalGroup(
            pnlAddDipsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddDipsMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(121, 121, 121))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddDipsMainLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(pnlAddDipsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAddDipsMainLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dteDipsAddDipsDate, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                    .addGroup(pnlAddDipsMainLayout.createSequentialGroup()
                        .addGroup(pnlAddDipsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddDipsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboDipsAddDipsProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboDipsAddDipsTank, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddDipsMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddDipsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAddDipsMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDipsAddDips)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDipsCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddDipsMainLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDipsAddDipsPreviousClosingDip, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                    .addGroup(pnlAddDipsMainLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDipsAddDipsOpeningDip)))
                .addGap(43, 43, 43))
        );

        pnlAddDipsMainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDipsAddDips, btnDipsCancel});

        pnlAddDipsMainLayout.setVerticalGroup(
            pnlAddDipsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddDipsMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGroup(pnlAddDipsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddDipsMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dteDipsAddDipsDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddDipsMainLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(pnlAddDipsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboDipsAddDipsProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddDipsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cboDipsAddDipsTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddDipsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDipsAddDipsPreviousClosingDip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddDipsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDipsAddDipsOpeningDip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddDipsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDipsCancel)
                    .addComponent(btnDipsAddDips))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnlAddDipsMainLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboDipsAddDipsProduct, cboDipsAddDipsTank, dteDipsAddDipsDate, txtDipsAddDipsOpeningDip, txtDipsAddDipsPreviousClosingDip});

        pnlAddDipsMainLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDipsAddDips, btnDipsCancel});

        javax.swing.GroupLayout dlgDipsAddDipsLayout = new javax.swing.GroupLayout(dlgDipsAddDips.getContentPane());
        dlgDipsAddDips.getContentPane().setLayout(dlgDipsAddDipsLayout);
        dlgDipsAddDipsLayout.setHorizontalGroup(
            dlgDipsAddDipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddDipsMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgDipsAddDipsLayout.setVerticalGroup(
            dlgDipsAddDipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddDipsMain, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel1.setText("Product");

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel2.setText("Tanks");

        cboDipsTanks.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel3.setText("From");

        dteDipsFrom.setDateFormatString("dd-MM-yyyy");
        dteDipsFrom.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel4.setText("To");

        dteDipsTo.setDateFormatString("dd-MM-yyyy");
        dteDipsTo.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel5.setText("DIPS");

        javax.swing.GroupLayout pnlDipsTopTitleLayout = new javax.swing.GroupLayout(pnlDipsTopTitle);
        pnlDipsTopTitle.setLayout(pnlDipsTopTitleLayout);
        pnlDipsTopTitleLayout.setHorizontalGroup(
            pnlDipsTopTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDipsTopTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(478, 478, 478))
        );
        pnlDipsTopTitleLayout.setVerticalGroup(
            pnlDipsTopTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        rbtDipsAll.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        rbtDipsAll.setSelected(true);
        rbtDipsAll.setText("All");
        rbtDipsAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDipsAllActionPerformed(evt);
            }
        });

        btnDipsView.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnDipsView.setMnemonic('V');
        btnDipsView.setText("View");
        btnDipsView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDipsViewActionPerformed(evt);
            }
        });

        chkDipsPetrolRegular.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        chkDipsPetrolRegular.setSelected(true);
        chkDipsPetrolRegular.setText("Petrol Regular");

        chkDipsPetrolSuper.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        chkDipsPetrolSuper.setSelected(true);
        chkDipsPetrolSuper.setText("Petrol Super");

        chkDipsDiesel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        chkDipsDiesel.setSelected(true);
        chkDipsDiesel.setText("Diesel");

        chkParaffin.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        chkParaffin.setSelected(true);
        chkParaffin.setText("Paraffin");

        javax.swing.GroupLayout pnlDipsTopLayout = new javax.swing.GroupLayout(pnlDipsTop);
        pnlDipsTop.setLayout(pnlDipsTopLayout);
        pnlDipsTopLayout.setHorizontalGroup(
            pnlDipsTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDipsTopLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(rbtDipsAll)
                .addGap(18, 18, 18)
                .addComponent(chkDipsPetrolRegular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDipsPetrolSuper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkDipsDiesel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkParaffin)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboDipsTanks, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dteDipsFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dteDipsTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDipsView)
                .addContainerGap(40, Short.MAX_VALUE))
            .addComponent(pnlDipsTopTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlDipsTopLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dteDipsFrom, dteDipsTo});

        pnlDipsTopLayout.setVerticalGroup(
            pnlDipsTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDipsTopLayout.createSequentialGroup()
                .addComponent(pnlDipsTopTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDipsTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dteDipsTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dteDipsFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDipsTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(cboDipsTanks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbtDipsAll)
                        .addComponent(chkDipsPetrolRegular)
                        .addComponent(chkDipsPetrolSuper)
                        .addComponent(chkDipsDiesel)
                        .addComponent(chkParaffin))
                    .addComponent(btnDipsView)))
        );

        tblDips.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        tblDips.setModel(tbmDips);
        tblDips.setGridColor(new java.awt.Color(0, 0, 255));
        tblDips.setRowHeight(20);
        tblDips.setSelectionForeground(new java.awt.Color(255, 0, 51));
        jScrollPane1.setViewportView(tblDips);

        javax.swing.GroupLayout pnlDipsMiddleLayout = new javax.swing.GroupLayout(pnlDipsMiddle);
        pnlDipsMiddle.setLayout(pnlDipsMiddleLayout);
        pnlDipsMiddleLayout.setHorizontalGroup(
            pnlDipsMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnlDipsMiddleLayout.setVerticalGroup(
            pnlDipsMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jButton1.setMnemonic('A');
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jButton2.setMnemonic('E');
        jButton2.setText("Edit");

        jButton3.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jButton3.setMnemonic('D');
        jButton3.setText("Delete");

        javax.swing.GroupLayout pnlDipsBottomLayout = new javax.swing.GroupLayout(pnlDipsBottom);
        pnlDipsBottom.setLayout(pnlDipsBottomLayout);
        pnlDipsBottomLayout.setHorizontalGroup(
            pnlDipsBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDipsBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pnlDipsBottomLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        pnlDipsBottomLayout.setVerticalGroup(
            pnlDipsBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDipsBottomLayout.createSequentialGroup()
                .addGroup(pnlDipsBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDipsMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDipsBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDipsTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDipsTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDipsMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDipsBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDipsViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDipsViewActionPerformed
        // View dips with filters applied
        try {
            populateDips();
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }//GEN-LAST:event_btnDipsViewActionPerformed

    private void rbtDipsAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDipsAllActionPerformed
        // Select checkboxes depending on value of All radio button
        if (rbtDipsAll.isSelected()) {
            chkDipsDiesel.setSelected(true);
            chkDipsPetrolRegular.setSelected(true);
            chkDipsPetrolSuper.setSelected(true);
            chkParaffin.setSelected(true);
        } else {
            chkDipsDiesel.setSelected(false);
            chkDipsPetrolRegular.setSelected(false);
            chkDipsPetrolSuper.setSelected(false);
            chkParaffin.setSelected(false);
        }
    }//GEN-LAST:event_rbtDipsAllActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add dips
        dlgDipsAddDips.setVisible(true);
        dlgDipsAddDips.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgDips;
    private javax.swing.JButton btnDipsAddDips;
    private javax.swing.JButton btnDipsCancel;
    private javax.swing.JButton btnDipsView;
    private javax.swing.JComboBox cboDipsAddDipsProduct;
    private javax.swing.JComboBox cboDipsAddDipsTank;
    private javax.swing.JComboBox cboDipsTanks;
    private javax.swing.JCheckBox chkDipsDiesel;
    private javax.swing.JCheckBox chkDipsPetrolRegular;
    private javax.swing.JCheckBox chkDipsPetrolSuper;
    private javax.swing.JCheckBox chkParaffin;
    private javax.swing.JDialog dlgDipsAddDips;
    private com.toedter.calendar.JDateChooser dteDipsAddDipsDate;
    private com.toedter.calendar.JDateChooser dteDipsFrom;
    private com.toedter.calendar.JDateChooser dteDipsTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlAddDipsMain;
    private javax.swing.JPanel pnlDipsBottom;
    private javax.swing.JPanel pnlDipsMiddle;
    private javax.swing.JPanel pnlDipsTop;
    private javax.swing.JPanel pnlDipsTopTitle;
    private javax.swing.JRadioButton rbtDipsAll;
    private javax.swing.JTable tblDips;
    private javax.swing.JTextField txtDipsAddDipsOpeningDip;
    private javax.swing.JTextField txtDipsAddDipsPreviousClosingDip;
    // End of variables declaration//GEN-END:variables
}
