/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package org.orpik.ui;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Locale;
import javax.imageio.ImageIO;
import org.orpik.core.Product;
import org.orpik.helper.HelperMainFrame;

/**
 *
 * @author Chemweno
 */
public class MainFrame extends javax.swing.JFrame {
    private HelperMainFrame helperMainFrame = new HelperMainFrame();
    
    private Dips dips = new Dips();
    private Sales sales =  new Sales();
    private Product products = new Product();
    private ReorderLevel reOrderLevel = new ReorderLevel();
    private ProductsUi productsUi = new ProductsUi();   
    private StockUi stockUi = new StockUi();

    /**
     * Creates new form Main
     */
    private Point screenCenterPoint = null;
    private Dimension screenSize = null;
    public MainFrame() {
        try{
        initComponents();
        //Calculate screen center point
        screenCenterPoint = getScreenCenterPoint();
        //Get screen size
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        //Set icon image
        setIconImage(ImageIO.read(getClass().getResource("/images/gas_pump_red_32.png")));
        //Place component on screen center
        //setComponentLocation();
        this.setLocationRelativeTo(null);
        //Set component resizable
        //setComponentResizable();
        //Set component maximum size
        //setComponentMaximumSize();
        //Set component preferred size
        //setComponentPrefferedSize();  
        //this.repaint();
        //this.setVisible(true);
        //populate products
        products.poulateProducts(cboNewPriceProducts);
        }catch(IOException ioException){
            ioException.printStackTrace();
        }catch(Exception exception){
            exception.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgNewPrices = new javax.swing.JDialog();
        pnlNewPricesMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboNewPriceProducts = new javax.swing.JComboBox();
        txtNewPricePrice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jButton10 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton15 = new javax.swing.JButton();
        tbpMainFrame = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniFileExit = new javax.swing.JMenuItem();
        mnuProducts = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuSales = new javax.swing.JMenu();
        mniViewSales = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        mnuDips = new javax.swing.JMenu();
        mniViewDips = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        mnuStocks = new javax.swing.JMenu();
        mniViewStock = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnuPrices = new javax.swing.JMenu();
        mniPricesSetNewPrices = new javax.swing.JMenuItem();
        mniPricesViewPriceHistory = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        mnuStaff = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        mnuCosts = new javax.swing.JMenu();
        mniAllCosts = new javax.swing.JMenuItem();
        mniRecurringCosts = new javax.swing.JMenuItem();
        mniNonRecurringCosts = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        mnuTools = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        dlgNewPrices.setMinimumSize(new java.awt.Dimension(370, 200));
        dlgNewPrices.setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel1.setText("Set New Prices");

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel2.setText("Product");

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel3.setText("Price");

        cboNewPriceProducts.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        txtNewPricePrice.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jButton1.setMnemonic('S');
        jButton1.setText("Save");

        jButton2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jButton2.setMnemonic('C');
        jButton2.setText("Cancel");

        javax.swing.GroupLayout pnlNewPricesMainLayout = new javax.swing.GroupLayout(pnlNewPricesMain);
        pnlNewPricesMain.setLayout(pnlNewPricesMainLayout);
        pnlNewPricesMainLayout.setHorizontalGroup(
            pnlNewPricesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewPricesMainLayout.createSequentialGroup()
                .addGroup(pnlNewPricesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNewPricesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlNewPricesMainLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboNewPriceProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNewPricesMainLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2))
                        .addGroup(pnlNewPricesMainLayout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNewPricePrice)))
                    .addGroup(pnlNewPricesMainLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlNewPricesMainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        pnlNewPricesMainLayout.setVerticalGroup(
            pnlNewPricesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewPricesMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNewPricesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboNewPriceProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlNewPricesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNewPricePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlNewPricesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlNewPricesMainLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        javax.swing.GroupLayout dlgNewPricesLayout = new javax.swing.GroupLayout(dlgNewPrices.getContentPane());
        dlgNewPrices.getContentPane().setLayout(dlgNewPricesLayout);
        dlgNewPricesLayout.setHorizontalGroup(
            dlgNewPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNewPricesMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dlgNewPricesLayout.setVerticalGroup(
            dlgNewPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNewPricesMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orpik Filling Station System");
        setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N

        jToolBar1.setRollover(true);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Information_24x24.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator1);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Information_24x24.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Information_24x24.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);
        jToolBar1.add(jSeparator4);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Information_24x24.png"))); // NOI18N
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Information_24x24.png"))); // NOI18N
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton7);
        jToolBar1.add(jSeparator6);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Information_24x24.png"))); // NOI18N
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Information_24x24.png"))); // NOI18N
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton9);
        jToolBar1.add(jSeparator7);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Information_24x24.png"))); // NOI18N
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton10);
        jToolBar1.add(jSeparator5);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Information_24x24.png"))); // NOI18N
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton11);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Information_24x24.png"))); // NOI18N
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton12);
        jToolBar1.add(jSeparator8);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Information_24x24.png"))); // NOI18N
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton13);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Information_24x24.png"))); // NOI18N
        jButton14.setFocusable(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton14);
        jToolBar1.add(jSeparator2);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Information_24x24.png"))); // NOI18N
        jButton15.setFocusable(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton15);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1078, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        mnuFile.setText("File");

        jMenuItem6.setText("Logout");
        mnuFile.add(jMenuItem6);
        mnuFile.add(jSeparator3);

        mniFileExit.setText("Exit");
        mniFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFileExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniFileExit);

        jMenuBar1.add(mnuFile);

        mnuProducts.setText("Products");

        jMenuItem14.setText("View Products");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        mnuProducts.add(jMenuItem14);

        jMenuItem1.setText("Add New Product ");
        mnuProducts.add(jMenuItem1);

        jMenuBar1.add(mnuProducts);

        mnuSales.setText("Sales");

        mniViewSales.setText("View All Sales");
        mniViewSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewSalesActionPerformed(evt);
            }
        });
        mnuSales.add(mniViewSales);

        jMenuItem8.setText("View Sales Per Staff");
        mnuSales.add(jMenuItem8);

        jMenuItem9.setText("View Sales Per Product");
        mnuSales.add(jMenuItem9);

        jMenuBar1.add(mnuSales);

        mnuDips.setText("Dips");

        mniViewDips.setText("Manage Dips");
        mniViewDips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewDipsActionPerformed(evt);
            }
        });
        mnuDips.add(mniViewDips);

        jMenuBar1.add(mnuDips);

        jMenu8.setText("Tanks");
        jMenuBar1.add(jMenu8);

        jMenu7.setText("Pumps");
        jMenuBar1.add(jMenu7);

        mnuStocks.setText("Stock");

        mniViewStock.setText("View Stock");
        mniViewStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewStockActionPerformed(evt);
            }
        });
        mnuStocks.add(mniViewStock);

        jMenuBar1.add(mnuStocks);

        jMenu6.setText("Variance");
        jMenuBar1.add(jMenu6);

        mnuPrices.setText("Prices");

        mniPricesSetNewPrices.setText("Set New Prices");
        mniPricesSetNewPrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPricesSetNewPricesActionPerformed(evt);
            }
        });
        mnuPrices.add(mniPricesSetNewPrices);

        mniPricesViewPriceHistory.setText("View Price History");
        mnuPrices.add(mniPricesViewPriceHistory);

        jMenuBar1.add(mnuPrices);

        jMenu9.setText("Profitability");
        jMenuBar1.add(jMenu9);

        jMenu10.setText("Debts");
        jMenuBar1.add(jMenu10);

        jMenu11.setText("Assets");

        jMenuItem10.setText("View Assets");
        jMenu11.add(jMenuItem10);

        jMenuBar1.add(jMenu11);

        mnuStaff.setText("Staff");

        jMenuItem7.setText("Shorts");
        mnuStaff.add(jMenuItem7);

        jMenuBar1.add(mnuStaff);

        jMenu4.setText("Customers");

        jMenuItem11.setText("View Customers");
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        mnuCosts.setText("Costs");

        mniAllCosts.setText("All Costs");
        mnuCosts.add(mniAllCosts);

        mniRecurringCosts.setText("Recurring Costs");
        mnuCosts.add(mniRecurringCosts);

        mniNonRecurringCosts.setText("Non-recurring Costs");
        mnuCosts.add(mniNonRecurringCosts);

        jMenuBar1.add(mnuCosts);

        mnuReports.setText("Reports");
        jMenuBar1.add(mnuReports);

        mnuTools.setText("Tools");
        jMenuBar1.add(mnuTools);

        jMenu3.setText("Help");

        jMenuItem12.setText("Help Contents");
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText("Help About");
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tbpMainFrame)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpMainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFileExitActionPerformed
        // Exit main frame
        helperMainFrame.exitWindow();
    }//GEN-LAST:event_mniFileExitActionPerformed

    private void mniViewDipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewDipsActionPerformed
        
        //Load data on table
        dips.populateDips();
        // View dips        
        helperMainFrame.addPanelToPaneTabbed("Dips", "appointment_missed.png", tbpMainFrame, dips);
      
    }//GEN-LAST:event_mniViewDipsActionPerformed

    private void mniViewSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewSalesActionPerformed
        // View all sales
        sales.prepareTable();
        //Add panel to tabbed pane
        helperMainFrame.addPanelToPaneTabbed("Sales", "appointment_missed.png", tbpMainFrame, sales);
    }//GEN-LAST:event_mniViewSalesActionPerformed

    private void mniPricesSetNewPricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPricesSetNewPricesActionPerformed
        //Set new prices
        //dlgNewPrices.setLocationRelativeTo(null);
        dlgNewPrices.setVisible(true);
        dlgNewPrices.setLocationRelativeTo(null);
    }//GEN-LAST:event_mniPricesSetNewPricesActionPerformed

    private void mniViewStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewStockActionPerformed
        // Show stock levels
        stockUi.prepareTable();
        //Add panel to tabbed pane
        helperMainFrame.addPanelToPaneTabbed("Stock Levels", "appointment_missed.png", tbpMainFrame, stockUi);       
        //Add data to stock table
        stockUi.populateTable();        
        
    }//GEN-LAST:event_mniViewStockActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // View all products
        productsUi.prepareTable();
        //Add panel to tabbed pane
        helperMainFrame.addPanelToPaneTabbed("Products", "appointment_missed.png", tbpMainFrame, productsUi);       
        //Add data to products table
        productsUi.populateTable();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboNewPriceProducts;
    private javax.swing.JDialog dlgNewPrices;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mniAllCosts;
    private javax.swing.JMenuItem mniFileExit;
    private javax.swing.JMenuItem mniNonRecurringCosts;
    private javax.swing.JMenuItem mniPricesSetNewPrices;
    private javax.swing.JMenuItem mniPricesViewPriceHistory;
    private javax.swing.JMenuItem mniRecurringCosts;
    private javax.swing.JMenuItem mniViewDips;
    private javax.swing.JMenuItem mniViewSales;
    private javax.swing.JMenuItem mniViewStock;
    private javax.swing.JMenu mnuCosts;
    private javax.swing.JMenu mnuDips;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuPrices;
    private javax.swing.JMenu mnuProducts;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenu mnuSales;
    private javax.swing.JMenu mnuStaff;
    private javax.swing.JMenu mnuStocks;
    private javax.swing.JMenu mnuTools;
    private javax.swing.JPanel pnlNewPricesMain;
    private javax.swing.JTabbedPane tbpMainFrame;
    private javax.swing.JTextField txtNewPricePrice;
    // End of variables declaration//GEN-END:variables
    
    //Settings
    
    //Get the screen center point 
    public Point getScreenCenterPoint() {        
        double xCoordinate = 0;
        double yCoordinate = 0;
        try {
            //Get screen size
            screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            //Get X coodinate
            xCoordinate = screenSize.getWidth();
            //Get Y coordinate
            yCoordinate = screenSize.getHeight();
            //Update screen center point
            screenCenterPoint = new Point((int) xCoordinate, (int) yCoordinate);
        } catch (Exception exception) {
        }
        return screenCenterPoint;
    }
    //Center component on screen
    private void setComponentLocation(){
        this.setLocation(screenCenterPoint);
    }
    //Get screen maximum size
    private void setComponentMaximumSize(){
        this.setMaximumSize(screenSize);
    }
    
    //Set screen component size
    private void setComponentPrefferedSize(){
        this.setPreferredSize(new Dimension(1074, 528));
    }
    //Set component resizable
    private void setComponentResizable(){
        this.setResizable(true);
    }
}
