/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.orpik.ui;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chemweno
 */
public class ReorderLevel extends javax.swing.JPanel {
    private DefaultTableModel tbmReOrderLevel = new DefaultTableModel();
    /**
     * Creates new form ReorderLevel
     */
    public ReorderLevel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReOrderLevelMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReOrderLevel = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tblReOrderLevel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        tblReOrderLevel.setModel(tbmReOrderLevel);
        jScrollPane1.setViewportView(tblReOrderLevel);

        jButton2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jButton2.setMnemonic('C');
        jButton2.setText("Close");

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 24)); // NOI18N
        jLabel1.setText("Re-Order Levels");

        javax.swing.GroupLayout pnlReOrderLevelMainLayout = new javax.swing.GroupLayout(pnlReOrderLevelMain);
        pnlReOrderLevelMain.setLayout(pnlReOrderLevelMainLayout);
        pnlReOrderLevelMainLayout.setHorizontalGroup(
            pnlReOrderLevelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReOrderLevelMainLayout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addGroup(pnlReOrderLevelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReOrderLevelMainLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReOrderLevelMainLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        pnlReOrderLevelMainLayout.setVerticalGroup(
            pnlReOrderLevelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReOrderLevelMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReOrderLevelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReOrderLevelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlReOrderLevelMain;
    private javax.swing.JTable tblReOrderLevel;
    // End of variables declaration//GEN-END:variables
}
