/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.orpik.ui;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.orpik.core.Product;
import org.orpik.core.Tanks;
import org.orpik.helper.HelperProducts;
import org.orpik.helper.HelperStock;

/**
 *
 * @author chemweno
 */
public class StockUi extends javax.swing.JPanel {
    private DefaultTableModel tbmStock = new DefaultTableModel();
    private HelperStock helperStock = new HelperStock();
    private Product product = new Product();
    /**
     * Creates new form ProductsUi
     */
    public StockUi() {
        initComponents();    
        //Set default button in edit product dialog
        dlgProducts.getRootPane().setDefaultButton(btnProductsSave);
    }

    public void prepareTable() {
        try {
            helperStock.prepareTable(tbmStock, tblStock, "Product Name", "Unit", "Re-Order Level", "Current Stock Level", "Date");
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    } 
    
    public void populateTable(){
        try{
            helperStock.populateStockOnTable(tbmStock, tblStock);
        }catch(Exception exception){
        exception.printStackTrace();
        }
    }
   /*  tblProducts = new javax.swing.JTable(tbmProducts) {
     public Component prepareRenderer(TableCellRenderer renderer, int row, int
     col) { Component comp = super.prepareRenderer(renderer, row, col); 
     if(row%2==0) {
     //Set even numbered rows to yellow 238-232-170
     comp.setBackground(new java.awt.Color(224, 224, 255)); 
     } else {
     //Set odd numbered rows to purple 147-112-219
     comp.setBackground(new java.awt.Color(255, 255, 255)); 
     } return comp; 
     }
     
     public boolean isCellEditable(int row, int column) {
     //Disable editing on all rows of the table
     return false;	  
     } 
     };	*/    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgProducts = new javax.swing.JDialog();
        lblEditProductTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnProductsSave = new javax.swing.JButton();
        btnProductsCancel = new javax.swing.JButton();
        cboProductsProductCategory = new javax.swing.JComboBox();
        cboProductsProductUnit = new javax.swing.JComboBox();
        txtProductsProductName = new javax.swing.JTextField();
        btnProductsAddProductCategory = new javax.swing.JButton();
        btnProductsAddProductUnit = new javax.swing.JButton();
        dlgStock = new javax.swing.JDialog();
        lblEditStockTitle = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnStockAdd = new javax.swing.JButton();
        btnStockCancel = new javax.swing.JButton();
        cboStockEntryType = new javax.swing.JComboBox();
        txtStockProductName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dteStockDateTaken = new com.toedter.calendar.JDateChooser();
        txtStockQuantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();
        btnEditStock = new javax.swing.JButton();
        btnAddStock = new javax.swing.JButton();
        btnDeleteStock = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        dlgProducts.setMinimumSize(new java.awt.Dimension(440, 250));
        dlgProducts.setResizable(false);

        lblEditProductTitle.setFont(new java.awt.Font("Arial Unicode MS", 0, 24)); // NOI18N
        lblEditProductTitle.setText("Edit Product");

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel3.setText("Product Name");

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel4.setText("Product Category");

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel5.setText("Product Unit");

        btnProductsSave.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnProductsSave.setMnemonic('S');
        btnProductsSave.setText("Save");

        btnProductsCancel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnProductsCancel.setMnemonic('C');
        btnProductsCancel.setText("Cancel");
        btnProductsCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsCancelActionPerformed(evt);
            }
        });

        cboProductsProductCategory.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        cboProductsProductUnit.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        txtProductsProductName.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        btnProductsAddProductCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add_16x16.png"))); // NOI18N
        btnProductsAddProductCategory.setToolTipText("Add new product category");

        btnProductsAddProductUnit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add_16x16.png"))); // NOI18N
        btnProductsAddProductUnit.setToolTipText("Add new product unit");

        javax.swing.GroupLayout dlgProductsLayout = new javax.swing.GroupLayout(dlgProducts.getContentPane());
        dlgProducts.getContentPane().setLayout(dlgProductsLayout);
        dlgProductsLayout.setHorizontalGroup(
            dlgProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dlgProductsLayout.createSequentialGroup()
                        .addComponent(btnProductsSave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProductsCancel))
                    .addGroup(dlgProductsLayout.createSequentialGroup()
                        .addGroup(dlgProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dlgProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProductsProductName)
                            .addComponent(cboProductsProductCategory, 0, 279, Short.MAX_VALUE)
                            .addComponent(cboProductsProductUnit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProductsAddProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductsAddProductUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgProductsLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(lblEditProductTitle)
                .addGap(160, 160, 160))
        );

        dlgProductsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnProductsCancel, btnProductsSave});

        dlgProductsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnProductsAddProductCategory, btnProductsAddProductUnit});

        dlgProductsLayout.setVerticalGroup(
            dlgProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgProductsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblEditProductTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProductsProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dlgProductsLayout.createSequentialGroup()
                        .addGroup(dlgProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboProductsProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProductsAddProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dlgProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cboProductsProductUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnProductsAddProductUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProductsSave)
                    .addComponent(btnProductsCancel))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        dlgProductsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnProductsAddProductCategory, btnProductsAddProductUnit});

        dlgStock.setMinimumSize(new java.awt.Dimension(440, 250));
        dlgStock.setResizable(false);

        lblEditStockTitle.setFont(new java.awt.Font("Arial Unicode MS", 0, 24)); // NOI18N
        lblEditStockTitle.setText("Edit Stock");

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel6.setText("Product Name");

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel7.setText("Entry Type");

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel8.setText("Quantity");

        btnStockAdd.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnStockAdd.setMnemonic('S');
        btnStockAdd.setText("Save");

        btnStockCancel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnStockCancel.setMnemonic('C');
        btnStockCancel.setText("Cancel");
        btnStockCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockCancelActionPerformed(evt);
            }
        });

        cboStockEntryType.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        cboStockEntryType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "In", "Out" }));

        txtStockProductName.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel9.setText("Date");

        dteStockDateTaken.setDateFormatString("dd-MM-yyyy");
        dteStockDateTaken.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        txtStockQuantity.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        javax.swing.GroupLayout dlgStockLayout = new javax.swing.GroupLayout(dlgStock.getContentPane());
        dlgStock.getContentPane().setLayout(dlgStockLayout);
        dlgStockLayout.setHorizontalGroup(
            dlgStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgStockLayout.createSequentialGroup()
                .addGroup(dlgStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgStockLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStockQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlgStockLayout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboStockEntryType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlgStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dlgStockLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnStockAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnStockCancel))
                            .addGroup(dlgStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlgStockLayout.createSequentialGroup()
                                    .addGap(65, 65, 65)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dteStockDateTaken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlgStockLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtStockProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgStockLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblEditStockTitle)
                .addGap(144, 144, 144))
        );
        dlgStockLayout.setVerticalGroup(
            dlgStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgStockLayout.createSequentialGroup()
                .addComponent(lblEditStockTitle)
                .addGap(17, 17, 17)
                .addGroup(dlgStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtStockProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(dteStockDateTaken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cboStockEntryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtStockQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStockAdd)
                    .addComponent(btnStockCancel))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tblStock.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        tblStock.setModel(tbmStock);
        tblStock.setGridColor(new java.awt.Color(0, 0, 255));
        tblStock.setRowHeight(20);
        tblStock.setSelectionForeground(new java.awt.Color(255, 0, 0));
        tblStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStock);

        btnEditStock.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnEditStock.setMnemonic('E');
        btnEditStock.setText("Edit Stock");
        btnEditStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStockActionPerformed(evt);
            }
        });

        btnAddStock.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnAddStock.setMnemonic('A');
        btnAddStock.setText("Add Stock");
        btnAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStockActionPerformed(evt);
            }
        });

        btnDeleteStock.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnDeleteStock.setMnemonic('D');
        btnDeleteStock.setText("Delete Stock");
        btnDeleteStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStockActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stock");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(455, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAddStock)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteStock)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(374, 374, 374))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditStock)
                        .addComponent(btnDeleteStock))
                    .addComponent(btnAddStock))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStockMouseClicked
        // Load product details on double click
        if(evt.getClickCount() == 2){
            launchEditProductdialog();
        }
    }//GEN-LAST:event_tblStockMouseClicked

    private void btnProductsCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsCancelActionPerformed
        // Dispose dialog
        dlgProducts.dispose();
    }//GEN-LAST:event_btnProductsCancelActionPerformed

    private void btnEditStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStockActionPerformed
        //Change dialog label text
        lblEditProductTitle.setText("Edit Stock");
        // Edit selected product
        launchEditProductdialog();
    }//GEN-LAST:event_btnEditStockActionPerformed

    private void btnAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStockActionPerformed
        // Change dialog label text
        lblEditProductTitle.setText("Add Stock");
        // Add new product
        launchAddProductdialog();
    }//GEN-LAST:event_btnAddStockActionPerformed

    private void btnDeleteStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteStockActionPerformed

    private void btnStockCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStockCancelActionPerformed
private void launchEditProductdialog(){
    try{
    //  if(evt.getClickCount() == 2){
        int selectecRowInIdex = 0;
        if(tblStock.getSelectedRow() != -1){
            selectecRowInIdex = tblStock.getSelectedRow();
          //   helperProducts.loadProductDetailsOnDialog(tblStock, dlgProducts, txtProductsProductName, cboProductsProductCategory, cboProductsProductUnit, selectecRowInIdex);
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row to edit a product.\nTo select, click on the row.", "No product selected", JOptionPane.WARNING_MESSAGE);
        } 
   // }        
    }catch(Exception exception){}
}

private void launchAddProductdialog(){
    try{    
           //Clear product name
           txtStockProductName.setText("");
           //Display dialog
           dlgStock.setVisible(true);
           //Center dialog
           dlgStock.setLocationRelativeTo(null);             
             
    }catch(Exception exception){}
}
    public void poulateProducts(JComboBox cbo) {
        ArrayList<Product> productsList = null;
        try {            
            //Remove all existing tanks in combo box
            cbo.removeAllItems();
           productsList = product.getFuelProducts();
           for(Product product : productsList){
               cbo.addItem(product.getProductName());
           }
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStock;
    private javax.swing.JButton btnDeleteStock;
    private javax.swing.JButton btnEditStock;
    private javax.swing.JButton btnProductsAddProductCategory;
    private javax.swing.JButton btnProductsAddProductUnit;
    private javax.swing.JButton btnProductsCancel;
    private javax.swing.JButton btnProductsSave;
    private javax.swing.JButton btnStockAdd;
    private javax.swing.JButton btnStockCancel;
    private javax.swing.JComboBox cboProductsProductCategory;
    private javax.swing.JComboBox cboProductsProductUnit;
    private javax.swing.JComboBox cboStockEntryType;
    private javax.swing.JDialog dlgProducts;
    private javax.swing.JDialog dlgStock;
    private com.toedter.calendar.JDateChooser dteStockDateTaken;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEditProductTitle;
    private javax.swing.JLabel lblEditStockTitle;
    private javax.swing.JTable tblStock;
    private javax.swing.JTextField txtProductsProductName;
    private javax.swing.JTextField txtStockProductName;
    private javax.swing.JTextField txtStockQuantity;
    // End of variables declaration//GEN-END:variables
}
