/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package org.orpik.ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chemweno
 */
public class StockLevel extends javax.swing.JDialog {

    private DefaultTableModel tbmStockLevel = new DefaultTableModel();
    /**
     * Creates new form StockLevel
     */
    public StockLevel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tblStockLevel.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        setTableColumns(tbmStockLevel, tblStockLevel);
        this.setPreferredSize(new Dimension(1088, 461));
        this.setResizable(true);
        this.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlStockLevelMain = new javax.swing.JPanel();
        pnlStockLevelTop = new javax.swing.JPanel();
        pnlStockLevelMid = new javax.swing.JPanel();
        scpStockLevel = new javax.swing.JScrollPane();
        tblStockLevel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout pnlStockLevelTopLayout = new javax.swing.GroupLayout(pnlStockLevelTop);
        pnlStockLevelTop.setLayout(pnlStockLevelTopLayout);
        pnlStockLevelTopLayout.setHorizontalGroup(
            pnlStockLevelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlStockLevelTopLayout.setVerticalGroup(
            pnlStockLevelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        pnlStockLevelMid.setLayout(new java.awt.GridBagLayout());

        tblStockLevel.setModel(tbmStockLevel);
        tblStockLevel.setFillsViewportHeight(true);
        scpStockLevel.setViewportView(tblStockLevel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1065;
        gridBagConstraints.ipady = 375;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlStockLevelMid.add(scpStockLevel, gridBagConstraints);

        javax.swing.GroupLayout pnlStockLevelMainLayout = new javax.swing.GroupLayout(pnlStockLevelMain);
        pnlStockLevelMain.setLayout(pnlStockLevelMainLayout);
        pnlStockLevelMainLayout.setHorizontalGroup(
            pnlStockLevelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStockLevelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlStockLevelMid, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
        );
        pnlStockLevelMainLayout.setVerticalGroup(
            pnlStockLevelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStockLevelMainLayout.createSequentialGroup()
                .addComponent(pnlStockLevelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStockLevelMid, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStockLevelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStockLevelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                StockLevel dialog = new StockLevel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlStockLevelMain;
    private javax.swing.JPanel pnlStockLevelMid;
    private javax.swing.JPanel pnlStockLevelTop;
    private javax.swing.JScrollPane scpStockLevel;
    private javax.swing.JTable tblStockLevel;
    // End of variables declaration//GEN-END:variables
//Set table
    private void setTableColumns(DefaultTableModel tableModel,javax.swing.JTable table){
        try{            
            tableModel.addColumn("Date");
            tableModel.addColumn("Pump");
            tableModel.addColumn("Product");
            tableModel.addColumn("Opening Manual");
            tableModel.addColumn("Closing Manual");
            tableModel.addColumn("Opening Electronic");
            tableModel.addColumn("Closing Electronic");
            tableModel.addColumn("Manual Quantity");
            tableModel.addColumn("Electronic Quantity");
            tableModel.addColumn("Price");
            tableModel.addColumn("Sales");
            tableModel.addColumn("Variation Manual");
            tableModel.addColumn("Variation Electronic");
        }catch(Exception exception){}
    }
    
}
