/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.orpik.ui;

import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import org.orpik.modular.ManageCommodities;
import org.orpik.settings.global.GuiManager;

/**
 *
 * @author chemweno
 */
public class ManageCommoditiesUi extends javax.swing.JPanel {

    private ManageCommodities manageCommodities = new ManageCommodities();
    private GuiManager guiManager = new GuiManager();
    private javax.swing.table.DefaultTableModel tbmIndicators = new javax.swing.table.DefaultTableModel();
    private int width = 750;
    private int height = 300;
    private int widthIndicatorCategoryDialog = 414;
    private int heightIndicatorCategoryDialog = 150;
    private int widthIndicatorDialog = 820;
    private int heightIndicatorDialog = 235;
    private int widthDeleteIndicatorDialog = 450;
    private int heightDeleteIndicatorDialog = 105;  

    /**
     * Creates new form ManageUser
     */
    public ManageCommoditiesUi() {
        initComponents();
        //Load role names
        /*manageUser.loadUserRoles(cboAddUserUserRole, cboEditUserUserRole);
        //Load languages
        manageUser.loadLanguages(cboAddCommodityUnit, cboEditUserWorkingLanguage);*/
        //Load indicator categories 
        manageCommodities.loadIndicatorCategories(cboAddCommodityCategory);
        //Load indicator units
        manageCommodities.loadIndicatorUnits(cboAddCommodityUnit);
        //Load all indicators
        manageCommodities.loadIndicators(tblManageCommoditiesAllCommodities, tbmIndicators);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgManageCommoditiesAddNewCommodity = new javax.swing.JDialog();
        pnlManageCommoditiessAddNewCommodityMain = new javax.swing.JPanel();
        pnlManageCommoditiesAddCommodityMiddle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAddIndicatorBusinessName = new javax.swing.JTextField();
        cboAddCommodityUnit = new javax.swing.JComboBox();
        cboAddCommodityCategory = new javax.swing.JComboBox();
        txtAddIndicatorName = new javax.swing.JTextField();
        btnAddCommodityAddCategory = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        chkAddCommodityMainMarkets = new javax.swing.JCheckBox();
        chkAddCommoditySlimsPart1 = new javax.swing.JCheckBox();
        chkAddCommoditySlimsPart2 = new javax.swing.JCheckBox();
        btnAddCommodityAddUnit = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnlManageUsersAddCommodityBottom = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));
        btnManageCommoditiesAddNewCommodity = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 32767));
        btnManageCommoditiesCancel = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));
        pnlManageCommoditiesAddCommodityTop = new javax.swing.JPanel();
        lblManageUsersTitle = new javax.swing.JLabel();
        dlgAddIndicatorCategory = new javax.swing.JDialog();
        pnlAddIndicatorCategoryMain = new javax.swing.JPanel();
        txtAddIndicatorCategoryName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnAddIndicatorCategorySave = new javax.swing.JButton();
        btnAddIndicatorCategoryCancel = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtAddIndicatorCategoryDescription = new javax.swing.JTextField();
        dlgAddIndicatorUnit = new javax.swing.JDialog();
        pnlAddIndicatorUnitMain = new javax.swing.JPanel();
        txtAddIndicatorUnitName = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnAddIndicatorUnitSave = new javax.swing.JButton();
        btnAddIndicatorUnitCancel = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtAddIndicatorUnitDescription = new javax.swing.JTextField();
        dlgDeleteIndicator = new javax.swing.JDialog();
        pnlDeleteIndicatorMain = new javax.swing.JPanel();
        btnDeleteIndicatorDelete = new javax.swing.JButton();
        btnDeleteIndicatorCancel = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txtDeleteIndicatorBusinessName = new javax.swing.JTextField();
        pnlManageCommoditiesMain = new javax.swing.JPanel();
        pnlManageCommoditiesTop = new javax.swing.JPanel();
        btnManageCommoditiesAddCommodity = new javax.swing.JButton();
        btnManageCommoditiesEditCommodity = new javax.swing.JButton();
        btnManageCommoditiesDeleteCommodity = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageCommoditiesAllCommodities = new javax.swing.JTable();

        dlgManageCommoditiesAddNewCommodity.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgManageCommoditiesAddNewCommodity.setModal(true);
        dlgManageCommoditiesAddNewCommodity.setResizable(false);

        pnlManageCommoditiessAddNewCommodityMain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel2.setText("Indicator Name");

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel3.setText("Business Name");

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel5.setText("Availability");

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel6.setText("Unit");

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel1.setText("Category");

        txtAddIndicatorBusinessName.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        cboAddCommodityUnit.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        cboAddCommodityCategory.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        txtAddIndicatorName.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        btnAddCommodityAddCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Add_16x16.png"))); // NOI18N
        btnAddCommodityAddCategory.setText("Add...");
        btnAddCommodityAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCommodityAddCategoryActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("*");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("*");

        chkAddCommodityMainMarkets.setText("Main Markets");

        chkAddCommoditySlimsPart1.setText("SLIMS Part 1");

        chkAddCommoditySlimsPart2.setText("SLIMS Part 2");
        chkAddCommoditySlimsPart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAddCommoditySlimsPart2ActionPerformed(evt);
            }
        });

        btnAddCommodityAddUnit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Add_16x16.png"))); // NOI18N
        btnAddCommodityAddUnit.setText("Add...");
        btnAddCommodityAddUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCommodityAddUnitActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("*");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setText("*");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 51, 51));
        jLabel17.setText("*");

        javax.swing.GroupLayout pnlManageCommoditiesAddCommodityMiddleLayout = new javax.swing.GroupLayout(pnlManageCommoditiesAddCommodityMiddle);
        pnlManageCommoditiesAddCommodityMiddle.setLayout(pnlManageCommoditiesAddCommodityMiddleLayout);
        pnlManageCommoditiesAddCommodityMiddleLayout.setHorizontalGroup(
            pnlManageCommoditiesAddCommodityMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createSequentialGroup()
                .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAddIndicatorName)
                    .addComponent(txtAddIndicatorBusinessName)
                    .addComponent(cboAddCommodityUnit, 0, 226, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createSequentialGroup()
                        .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createSequentialGroup()
                                .addComponent(cboAddCommodityCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddCommodityAddCategory))
                            .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createSequentialGroup()
                                .addComponent(chkAddCommodityMainMarkets)
                                .addGap(18, 18, 18)
                                .addComponent(chkAddCommoditySlimsPart1)
                                .addGap(18, 18, 18)
                                .addComponent(chkAddCommoditySlimsPart2))))
                    .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createSequentialGroup()
                        .addComponent(btnAddCommodityAddUnit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlManageCommoditiesAddCommodityMiddleLayout.setVerticalGroup(
            pnlManageCommoditiesAddCommodityMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createSequentialGroup()
                .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddIndicatorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13)
                            .addComponent(cboAddCommodityCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnAddCommodityAddCategory))
                        .addGap(18, 18, 18)
                        .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddIndicatorBusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel14)
                            .addComponent(jLabel5)
                            .addComponent(chkAddCommodityMainMarkets)
                            .addComponent(chkAddCommoditySlimsPart1)
                            .addComponent(chkAddCommoditySlimsPart2)
                            .addComponent(jLabel16))
                        .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboAddCommodityUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(btnAddCommodityAddUnit)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageCommoditiesAddCommodityMiddleLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))))
                    .addGroup(pnlManageCommoditiesAddCommodityMiddleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlManageUsersAddCommodityBottom.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlManageUsersAddCommodityBottom.setLayout(new java.awt.GridLayout(1, 0));
        pnlManageUsersAddCommodityBottom.add(filler2);

        btnManageCommoditiesAddNewCommodity.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnManageCommoditiesAddNewCommodity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Save_16x16.png"))); // NOI18N
        btnManageCommoditiesAddNewCommodity.setMnemonic('N');
        btnManageCommoditiesAddNewCommodity.setText("Save");
        btnManageCommoditiesAddNewCommodity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCommoditiesAddNewCommodityActionPerformed(evt);
            }
        });
        pnlManageUsersAddCommodityBottom.add(btnManageCommoditiesAddNewCommodity);
        pnlManageUsersAddCommodityBottom.add(filler1);

        btnManageCommoditiesCancel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnManageCommoditiesCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Cancel_16x16.png"))); // NOI18N
        btnManageCommoditiesCancel.setMnemonic('C');
        btnManageCommoditiesCancel.setText("Cancel");
        btnManageCommoditiesCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCommoditiesCancelActionPerformed(evt);
            }
        });
        pnlManageUsersAddCommodityBottom.add(btnManageCommoditiesCancel);
        pnlManageUsersAddCommodityBottom.add(filler3);

        lblManageUsersTitle.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        lblManageUsersTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageUsersTitle.setText("Add Indicator");

        javax.swing.GroupLayout pnlManageCommoditiesAddCommodityTopLayout = new javax.swing.GroupLayout(pnlManageCommoditiesAddCommodityTop);
        pnlManageCommoditiesAddCommodityTop.setLayout(pnlManageCommoditiesAddCommodityTopLayout);
        pnlManageCommoditiesAddCommodityTopLayout.setHorizontalGroup(
            pnlManageCommoditiesAddCommodityTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageCommoditiesAddCommodityTopLayout.createSequentialGroup()
                .addContainerGap(349, Short.MAX_VALUE)
                .addComponent(lblManageUsersTitle)
                .addGap(284, 284, 284))
        );
        pnlManageCommoditiesAddCommodityTopLayout.setVerticalGroup(
            pnlManageCommoditiesAddCommodityTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageCommoditiesAddCommodityTopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblManageUsersTitle))
        );

        javax.swing.GroupLayout pnlManageCommoditiessAddNewCommodityMainLayout = new javax.swing.GroupLayout(pnlManageCommoditiessAddNewCommodityMain);
        pnlManageCommoditiessAddNewCommodityMain.setLayout(pnlManageCommoditiessAddNewCommodityMainLayout);
        pnlManageCommoditiessAddNewCommodityMainLayout.setHorizontalGroup(
            pnlManageCommoditiessAddNewCommodityMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageCommoditiesAddCommodityTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlManageCommoditiesAddCommodityMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlManageUsersAddCommodityBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlManageCommoditiessAddNewCommodityMainLayout.setVerticalGroup(
            pnlManageCommoditiessAddNewCommodityMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageCommoditiessAddNewCommodityMainLayout.createSequentialGroup()
                .addComponent(pnlManageCommoditiesAddCommodityTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlManageCommoditiesAddCommodityMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlManageUsersAddCommodityBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgManageCommoditiesAddNewCommodityLayout = new javax.swing.GroupLayout(dlgManageCommoditiesAddNewCommodity.getContentPane());
        dlgManageCommoditiesAddNewCommodity.getContentPane().setLayout(dlgManageCommoditiesAddNewCommodityLayout);
        dlgManageCommoditiesAddNewCommodityLayout.setHorizontalGroup(
            dlgManageCommoditiesAddNewCommodityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageCommoditiessAddNewCommodityMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgManageCommoditiesAddNewCommodityLayout.setVerticalGroup(
            dlgManageCommoditiesAddNewCommodityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageCommoditiessAddNewCommodityMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dlgAddIndicatorCategory.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgAddIndicatorCategory.setTitle("Add New Indicator Category");
        dlgAddIndicatorCategory.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dlgAddIndicatorCategory.setResizable(false);

        jLabel19.setText("Category Name");

        btnAddIndicatorCategorySave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Save_16x16.png"))); // NOI18N
        btnAddIndicatorCategorySave.setMnemonic('S');
        btnAddIndicatorCategorySave.setText("Save");
        btnAddIndicatorCategorySave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIndicatorCategorySaveActionPerformed(evt);
            }
        });

        btnAddIndicatorCategoryCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Cancel_16x16.png"))); // NOI18N
        btnAddIndicatorCategoryCancel.setMnemonic('C');
        btnAddIndicatorCategoryCancel.setText("Cancel");
        btnAddIndicatorCategoryCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIndicatorCategoryCancelActionPerformed(evt);
            }
        });

        jLabel20.setText("Description");

        javax.swing.GroupLayout pnlAddIndicatorCategoryMainLayout = new javax.swing.GroupLayout(pnlAddIndicatorCategoryMain);
        pnlAddIndicatorCategoryMain.setLayout(pnlAddIndicatorCategoryMainLayout);
        pnlAddIndicatorCategoryMainLayout.setHorizontalGroup(
            pnlAddIndicatorCategoryMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddIndicatorCategoryMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddIndicatorCategoryMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddIndicatorCategoryMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddIndicatorCategoryMainLayout.createSequentialGroup()
                        .addComponent(btnAddIndicatorCategorySave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddIndicatorCategoryCancel)
                        .addContainerGap(149, Short.MAX_VALUE))
                    .addGroup(pnlAddIndicatorCategoryMainLayout.createSequentialGroup()
                        .addGroup(pnlAddIndicatorCategoryMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAddIndicatorCategoryDescription, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddIndicatorCategoryName))
                        .addGap(39, 39, 39))))
        );

        pnlAddIndicatorCategoryMainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddIndicatorCategoryCancel, btnAddIndicatorCategorySave});

        pnlAddIndicatorCategoryMainLayout.setVerticalGroup(
            pnlAddIndicatorCategoryMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddIndicatorCategoryMainLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlAddIndicatorCategoryMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddIndicatorCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddIndicatorCategoryMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddIndicatorCategoryDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(pnlAddIndicatorCategoryMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddIndicatorCategorySave)
                    .addComponent(btnAddIndicatorCategoryCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAddIndicatorCategoryMainLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddIndicatorCategoryCancel, btnAddIndicatorCategorySave});

        javax.swing.GroupLayout dlgAddIndicatorCategoryLayout = new javax.swing.GroupLayout(dlgAddIndicatorCategory.getContentPane());
        dlgAddIndicatorCategory.getContentPane().setLayout(dlgAddIndicatorCategoryLayout);
        dlgAddIndicatorCategoryLayout.setHorizontalGroup(
            dlgAddIndicatorCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddIndicatorCategoryMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgAddIndicatorCategoryLayout.setVerticalGroup(
            dlgAddIndicatorCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddIndicatorCategoryMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dlgAddIndicatorUnit.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgAddIndicatorUnit.setTitle("Add New Indicator Unit");
        dlgAddIndicatorUnit.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dlgAddIndicatorUnit.setResizable(false);

        jLabel21.setText("Indicator Unit Name");

        btnAddIndicatorUnitSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Save_16x16.png"))); // NOI18N
        btnAddIndicatorUnitSave.setMnemonic('S');
        btnAddIndicatorUnitSave.setText("Save");
        btnAddIndicatorUnitSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIndicatorUnitSaveActionPerformed(evt);
            }
        });

        btnAddIndicatorUnitCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Cancel_16x16.png"))); // NOI18N
        btnAddIndicatorUnitCancel.setMnemonic('C');
        btnAddIndicatorUnitCancel.setText("Cancel");
        btnAddIndicatorUnitCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIndicatorUnitCancelActionPerformed(evt);
            }
        });

        jLabel22.setText("Description");

        javax.swing.GroupLayout pnlAddIndicatorUnitMainLayout = new javax.swing.GroupLayout(pnlAddIndicatorUnitMain);
        pnlAddIndicatorUnitMain.setLayout(pnlAddIndicatorUnitMainLayout);
        pnlAddIndicatorUnitMainLayout.setHorizontalGroup(
            pnlAddIndicatorUnitMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddIndicatorUnitMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddIndicatorUnitMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddIndicatorUnitMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddIndicatorUnitMainLayout.createSequentialGroup()
                        .addComponent(btnAddIndicatorUnitSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddIndicatorUnitCancel)
                        .addContainerGap(114, Short.MAX_VALUE))
                    .addGroup(pnlAddIndicatorUnitMainLayout.createSequentialGroup()
                        .addGroup(pnlAddIndicatorUnitMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAddIndicatorUnitDescription, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddIndicatorUnitName))
                        .addGap(39, 39, 39))))
        );
        pnlAddIndicatorUnitMainLayout.setVerticalGroup(
            pnlAddIndicatorUnitMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddIndicatorUnitMainLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlAddIndicatorUnitMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddIndicatorUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddIndicatorUnitMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddIndicatorUnitDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(pnlAddIndicatorUnitMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddIndicatorUnitSave)
                    .addComponent(btnAddIndicatorUnitCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgAddIndicatorUnitLayout = new javax.swing.GroupLayout(dlgAddIndicatorUnit.getContentPane());
        dlgAddIndicatorUnit.getContentPane().setLayout(dlgAddIndicatorUnitLayout);
        dlgAddIndicatorUnitLayout.setHorizontalGroup(
            dlgAddIndicatorUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddIndicatorUnitMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgAddIndicatorUnitLayout.setVerticalGroup(
            dlgAddIndicatorUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddIndicatorUnitMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dlgDeleteIndicator.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgDeleteIndicator.setTitle("Delete Indicator");
        dlgDeleteIndicator.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dlgDeleteIndicator.setResizable(false);

        btnDeleteIndicatorDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Delete_16x16.png"))); // NOI18N
        btnDeleteIndicatorDelete.setMnemonic('R');
        btnDeleteIndicatorDelete.setText("Delete Indicator");
        btnDeleteIndicatorDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteIndicatorDeleteActionPerformed(evt);
            }
        });

        btnDeleteIndicatorCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Cancel_16x16.png"))); // NOI18N
        btnDeleteIndicatorCancel.setMnemonic('C');
        btnDeleteIndicatorCancel.setText("Cancel");
        btnDeleteIndicatorCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteIndicatorCancelActionPerformed(evt);
            }
        });

        jLabel28.setText("Indicator Business Name");

        txtDeleteIndicatorBusinessName.setEditable(false);

        javax.swing.GroupLayout pnlDeleteIndicatorMainLayout = new javax.swing.GroupLayout(pnlDeleteIndicatorMain);
        pnlDeleteIndicatorMain.setLayout(pnlDeleteIndicatorMainLayout);
        pnlDeleteIndicatorMainLayout.setHorizontalGroup(
            pnlDeleteIndicatorMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDeleteIndicatorMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDeleteIndicatorMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeleteIndicatorMainLayout.createSequentialGroup()
                        .addComponent(btnDeleteIndicatorDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteIndicatorCancel))
                    .addComponent(txtDeleteIndicatorBusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        pnlDeleteIndicatorMainLayout.setVerticalGroup(
            pnlDeleteIndicatorMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteIndicatorMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDeleteIndicatorMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtDeleteIndicatorBusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDeleteIndicatorMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteIndicatorDelete)
                    .addComponent(btnDeleteIndicatorCancel))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout dlgDeleteIndicatorLayout = new javax.swing.GroupLayout(dlgDeleteIndicator.getContentPane());
        dlgDeleteIndicator.getContentPane().setLayout(dlgDeleteIndicatorLayout);
        dlgDeleteIndicatorLayout.setHorizontalGroup(
            dlgDeleteIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDeleteIndicatorMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgDeleteIndicatorLayout.setVerticalGroup(
            dlgDeleteIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDeleteIndicatorMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnManageCommoditiesAddCommodity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Add_16x16.png"))); // NOI18N
        btnManageCommoditiesAddCommodity.setMnemonic('A');
        btnManageCommoditiesAddCommodity.setText("Add Indicator");
        btnManageCommoditiesAddCommodity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCommoditiesAddCommodityActionPerformed(evt);
            }
        });

        btnManageCommoditiesEditCommodity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Edit_16x16.png"))); // NOI18N
        btnManageCommoditiesEditCommodity.setMnemonic('E');
        btnManageCommoditiesEditCommodity.setText("Edit Indicator");
        btnManageCommoditiesEditCommodity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCommoditiesEditCommodityActionPerformed(evt);
            }
        });

        btnManageCommoditiesDeleteCommodity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Delete_16x16.png"))); // NOI18N
        btnManageCommoditiesDeleteCommodity.setMnemonic('D');
        btnManageCommoditiesDeleteCommodity.setText("Delete Indicator");
        btnManageCommoditiesDeleteCommodity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCommoditiesDeleteCommodityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlManageCommoditiesTopLayout = new javax.swing.GroupLayout(pnlManageCommoditiesTop);
        pnlManageCommoditiesTop.setLayout(pnlManageCommoditiesTopLayout);
        pnlManageCommoditiesTopLayout.setHorizontalGroup(
            pnlManageCommoditiesTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageCommoditiesTopLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnManageCommoditiesAddCommodity)
                .addGap(18, 18, 18)
                .addComponent(btnManageCommoditiesEditCommodity)
                .addGap(18, 18, 18)
                .addComponent(btnManageCommoditiesDeleteCommodity)
                .addContainerGap(413, Short.MAX_VALUE))
        );
        pnlManageCommoditiesTopLayout.setVerticalGroup(
            pnlManageCommoditiesTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageCommoditiesTopLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnlManageCommoditiesTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageCommoditiesAddCommodity)
                    .addComponent(btnManageCommoditiesEditCommodity)
                    .addComponent(btnManageCommoditiesDeleteCommodity))
                .addContainerGap())
        );

        tblManageCommoditiesAllCommodities.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        tblManageCommoditiesAllCommodities.setModel(tbmIndicators);
        tblManageCommoditiesAllCommodities.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblManageCommoditiesAllCommodities.setGridColor(new java.awt.Color(0, 51, 255));
        tblManageCommoditiesAllCommodities.setRowHeight(25);
        tblManageCommoditiesAllCommodities.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblManageCommoditiesAllCommodities);

        javax.swing.GroupLayout pnlManageCommoditiesMainLayout = new javax.swing.GroupLayout(pnlManageCommoditiesMain);
        pnlManageCommoditiesMain.setLayout(pnlManageCommoditiesMainLayout);
        pnlManageCommoditiesMainLayout.setHorizontalGroup(
            pnlManageCommoditiesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageCommoditiesTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        pnlManageCommoditiesMainLayout.setVerticalGroup(
            pnlManageCommoditiesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageCommoditiesMainLayout.createSequentialGroup()
                .addComponent(pnlManageCommoditiesTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageCommoditiesMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageCommoditiesMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCommoditiesAddCommodityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCommoditiesAddCommodityActionPerformed
        //Set dialog title to Add
        lblManageUsersTitle.setText("Add Indicator");
        // Set add user dialog size
        dlgManageCommoditiesAddNewCommodity.setSize(widthIndicatorDialog, heightIndicatorDialog);
        // Set add user dialog location
        dlgManageCommoditiesAddNewCommodity.setLocationRelativeTo(null);
        // Launch add user dialog
        dlgManageCommoditiesAddNewCommodity.setVisible(true);
        //Set default button
    }//GEN-LAST:event_btnManageCommoditiesAddCommodityActionPerformed

    private void btnManageCommoditiesAddNewCommodityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCommoditiesAddNewCommodityActionPerformed
        int result = 10;
        int indicatorApplicationId = 0;
        int indicatorUnitId = 0;
        int indicatorCategoryId = 0;
        String indicatorName = "";
        String indicatorBusinessName = "";
        String indicatorUnit = "";
        String indicatorCategory = "";

        //Get values
        indicatorName = txtAddIndicatorName.getText();
        indicatorBusinessName = txtAddIndicatorBusinessName.getText();
        indicatorCategory = cboAddCommodityCategory.getSelectedItem().toString();
        indicatorUnit = cboAddCommodityUnit.getSelectedItem().toString();
        indicatorApplicationId = getApplicationId(chkAddCommodityMainMarkets, chkAddCommoditySlimsPart1, chkAddCommoditySlimsPart2);
        indicatorUnitId = manageCommodities.getIndicatorUnitId(indicatorUnit);
        indicatorCategoryId = manageCommodities.getIndicatorCategoryId(indicatorCategory);
        
        //Check application id
        if(indicatorApplicationId != 0){
            result = manageCommodities.insertIndicator(indicatorName, indicatorBusinessName, indicatorUnitId, indicatorCategoryId, 
                    indicatorApplicationId);
            if(result > 0){
                JOptionPane.showMessageDialog(null, "Indicator saved successfully", "Saving Indicator",
                    JOptionPane.INFORMATION_MESSAGE); 
            }else{
                JOptionPane.showMessageDialog(null, "Indicator saving failed. Please try again", "Saving Indicator",
                    JOptionPane.WARNING_MESSAGE); 
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select indicator availability", "Saving Indicator",
                    JOptionPane.WARNING_MESSAGE);            
        }
    }//GEN-LAST:event_btnManageCommoditiesAddNewCommodityActionPerformed

    private void btnManageCommoditiesCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCommoditiesCancelActionPerformed
        // Dispose dialog
        dlgManageCommoditiesAddNewCommodity.dispose();
    }//GEN-LAST:event_btnManageCommoditiesCancelActionPerformed

    private void btnAddIndicatorCategorySaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIndicatorCategorySaveActionPerformed
        // Add indicator category
        int result = 0;
        result = manageCommodities.addIndicatorCategory(txtAddIndicatorCategoryName.getText(), txtAddIndicatorCategoryDescription.getText());
        if (result > 0) {
            JOptionPane.showMessageDialog(null, "New indicator category added successfully", "Add Indicator Category",
                    JOptionPane.INFORMATION_MESSAGE);
            //Add new indicator to combo box
            cboAddCommodityCategory.addItem(txtAddIndicatorCategoryName.getText());
            //Set new category as selected item
            cboAddCommodityCategory.setSelectedItem(txtAddIndicatorCategoryName.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Indicator category was not added."
                    + "\nPlease seek assistance from system administrator",
                    "Add Indicator Category",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAddIndicatorCategorySaveActionPerformed

    private void btnAddCommodityAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCommodityAddCategoryActionPerformed
        // Launch dialog
        manageCommodities.launchDialog(dlgAddIndicatorCategory, widthIndicatorCategoryDialog, heightIndicatorCategoryDialog);
    }//GEN-LAST:event_btnAddCommodityAddCategoryActionPerformed

    private void btnAddIndicatorCategoryCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIndicatorCategoryCancelActionPerformed
        // Dispose indicator category dialog
        dlgAddIndicatorCategory.dispose();
    }//GEN-LAST:event_btnAddIndicatorCategoryCancelActionPerformed

    private void btnAddIndicatorUnitSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIndicatorUnitSaveActionPerformed
        // Add indicator unit
        int result = 0;
        result = manageCommodities.addIndicatorUnit(txtAddIndicatorUnitName.getText(), txtAddIndicatorUnitDescription.getText());
        if (result > 0) {
            JOptionPane.showMessageDialog(null, "Indicator unit saved successfully", "Add Indicator Unit",
                    JOptionPane.INFORMATION_MESSAGE);
            //Add indicator unit to combo box
            cboAddCommodityUnit.addItem(txtAddIndicatorUnitName.getText());
            //Set new indicator unit as selected item
            cboAddCommodityUnit.setSelectedItem(txtAddIndicatorUnitName.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Indicator unit was not added.\nPlease seek assistance from system administrator",
                    "Add Add Indicator Unit", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAddIndicatorUnitSaveActionPerformed

    private void btnAddIndicatorUnitCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIndicatorUnitCancelActionPerformed
        //Dispose indicator unit dialog
        dlgAddIndicatorUnit.dispose();
    }//GEN-LAST:event_btnAddIndicatorUnitCancelActionPerformed

    private void btnDeleteIndicatorDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteIndicatorDeleteActionPerformed
        // Delete indicator
        int result = 0;
        int indicatorId = 0;

        indicatorId = manageCommodities.getIndicatorId(tblManageCommoditiesAllCommodities);
        result = manageCommodities.deleteIndicator(indicatorId);
        if (result > 0) {
            //Load all indicators 
            manageCommodities.loadIndicators(tblManageCommoditiesAllCommodities, tbmIndicators);
            JOptionPane.showMessageDialog(null, "Indicator deleted successfully", "Delete Indicator",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Deleting indicator not successful", "Delete Indicator",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteIndicatorDeleteActionPerformed

    private void btnDeleteIndicatorCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteIndicatorCancelActionPerformed
        // Dispose delete user dialog
        dlgDeleteIndicator.dispose();
    }//GEN-LAST:event_btnDeleteIndicatorCancelActionPerformed

    private void btnManageCommoditiesDeleteCommodityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCommoditiesDeleteCommodityActionPerformed
        // Delete indicator        
        int indicatorId = 0;
        int selectedRow = 0;
        String indicatorBusinessName = "";

        selectedRow = tblManageCommoditiesAllCommodities.getSelectedRow();
        //Check if user has selected a row
        if (selectedRow > -1) {
            //Get indicator id
            indicatorId = manageCommodities.getIndicatorId(tblManageCommoditiesAllCommodities);
            indicatorBusinessName = tblManageCommoditiesAllCommodities.getValueAt(selectedRow, 1).toString();
            txtDeleteIndicatorBusinessName.setText(indicatorBusinessName);
            
            //Launch dialog
            manageCommodities.launchDialog(dlgDeleteIndicator, widthDeleteIndicatorDialog, heightDeleteIndicatorDialog);
        } else {
            //No row is selected
            JOptionPane.showMessageDialog(null, "Select indicator row whose indicator you wish to delete", "Delete Indicator",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnManageCommoditiesDeleteCommodityActionPerformed

    private void btnManageCommoditiesEditCommodityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCommoditiesEditCommodityActionPerformed
        // Launch edit user dialog
        int indicatorId = 0;
        //Check whether user selected a row
        if (tblManageCommoditiesAllCommodities.getSelectedRow() > -1) {
            //Get indicator id
            indicatorId = manageCommodities.getIndicatorId(tblManageCommoditiesAllCommodities);
            //populate username
            //txtEditUserUsername.setText(manageUser.getUsername(userId));
            //Populate all other user details
            manageCommodities.loadIndicators(indicatorId, txtAddIndicatorName, txtAddIndicatorBusinessName, 
                    cboAddCommodityCategory, cboAddCommodityUnit, chkAddCommodityMainMarkets, chkAddCommoditySlimsPart1, 
                    chkAddCommoditySlimsPart2);   
            
            // Launch edit indicator
            lblManageUsersTitle.setText("Edit Indicator");
            manageCommodities.launchDialog(dlgManageCommoditiesAddNewCommodity, widthIndicatorDialog, heightIndicatorDialog);
            
        } else {
            //No row was selected
            JOptionPane.showMessageDialog(null, "Select indicator row to edit indicator details", "Edit Indicator",
                    JOptionPane.INFORMATION_MESSAGE);
        }      
    }//GEN-LAST:event_btnManageCommoditiesEditCommodityActionPerformed

    private void chkAddCommoditySlimsPart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAddCommoditySlimsPart2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAddCommoditySlimsPart2ActionPerformed

    private void btnAddCommodityAddUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCommodityAddUnitActionPerformed
        // Launch dialog
        manageCommodities.launchDialog(dlgAddIndicatorUnit, widthIndicatorCategoryDialog, heightIndicatorCategoryDialog);
    }//GEN-LAST:event_btnAddCommodityAddUnitActionPerformed

    //Get application id
    private int getApplicationId(JCheckBox chkMarkets, JCheckBox chkSlims1, JCheckBox chkSlims2){
        int applicationId = 0;
        try{
            if(chkMarkets.isSelected()){
                applicationId = 1;
            }
            if(chkSlims1.isSelected()){
                applicationId = 2;                
            }
            if(chkMarkets.isSelected() && chkSlims1.isSelected()){
                applicationId = 3;
            }
            if(chkSlims2.isSelected()){
                applicationId = 4;
            }   
            if(chkSlims1.isSelected() && chkSlims2.isSelected()){
                applicationId = 5;
            }  
            if(chkMarkets.isSelected() && chkSlims2.isSelected()){
                applicationId = 6;
            }       
            if(chkMarkets.isSelected() && chkSlims1.isSelected() && chkSlims2.isSelected()){
                applicationId = 7;
            }              
        }catch(Exception exception){}
        return applicationId;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCommodityAddCategory;
    private javax.swing.JButton btnAddCommodityAddUnit;
    private javax.swing.JButton btnAddIndicatorCategoryCancel;
    private javax.swing.JButton btnAddIndicatorCategorySave;
    private javax.swing.JButton btnAddIndicatorUnitCancel;
    private javax.swing.JButton btnAddIndicatorUnitSave;
    private javax.swing.JButton btnDeleteIndicatorCancel;
    private javax.swing.JButton btnDeleteIndicatorDelete;
    private javax.swing.JButton btnManageCommoditiesAddCommodity;
    private javax.swing.JButton btnManageCommoditiesAddNewCommodity;
    private javax.swing.JButton btnManageCommoditiesCancel;
    private javax.swing.JButton btnManageCommoditiesDeleteCommodity;
    private javax.swing.JButton btnManageCommoditiesEditCommodity;
    private javax.swing.JComboBox cboAddCommodityCategory;
    private javax.swing.JComboBox cboAddCommodityUnit;
    private javax.swing.JCheckBox chkAddCommodityMainMarkets;
    private javax.swing.JCheckBox chkAddCommoditySlimsPart1;
    private javax.swing.JCheckBox chkAddCommoditySlimsPart2;
    private javax.swing.JDialog dlgAddIndicatorCategory;
    private javax.swing.JDialog dlgAddIndicatorUnit;
    private javax.swing.JDialog dlgDeleteIndicator;
    private javax.swing.JDialog dlgManageCommoditiesAddNewCommodity;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManageUsersTitle;
    private javax.swing.JPanel pnlAddIndicatorCategoryMain;
    private javax.swing.JPanel pnlAddIndicatorUnitMain;
    private javax.swing.JPanel pnlDeleteIndicatorMain;
    private javax.swing.JPanel pnlManageCommoditiesAddCommodityMiddle;
    private javax.swing.JPanel pnlManageCommoditiesAddCommodityTop;
    public javax.swing.JPanel pnlManageCommoditiesMain;
    private javax.swing.JPanel pnlManageCommoditiesTop;
    private javax.swing.JPanel pnlManageCommoditiessAddNewCommodityMain;
    private javax.swing.JPanel pnlManageUsersAddCommodityBottom;
    private javax.swing.JTable tblManageCommoditiesAllCommodities;
    private javax.swing.JTextField txtAddIndicatorBusinessName;
    private javax.swing.JTextField txtAddIndicatorCategoryDescription;
    private javax.swing.JTextField txtAddIndicatorCategoryName;
    private javax.swing.JTextField txtAddIndicatorName;
    private javax.swing.JTextField txtAddIndicatorUnitDescription;
    private javax.swing.JTextField txtAddIndicatorUnitName;
    private javax.swing.JTextField txtDeleteIndicatorBusinessName;
    // End of variables declaration//GEN-END:variables
}
