/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.orpik.ui;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import org.orpik.location.District;
import org.orpik.modular.ManageMarkets;
import org.orpik.people.FieldAnalyst;
import org.orpik.settings.global.GuiManager;

/**
 *
 * @author chemweno
 */
public class ManageMarketsUi extends javax.swing.JPanel {

    private ManageMarkets manageMarkets = new ManageMarkets();
    private GuiManager guiManager = new GuiManager();
    private javax.swing.table.DefaultTableModel tbmMarkets = new javax.swing.table.DefaultTableModel();
    private FieldAnalyst fieldAnalyst = new FieldAnalyst();
    private District district = new District();
    private int width = 750;
    private int height = 170;
    private int widthIndicatorCategoryDialog = 414;
    private int heightIndicatorCategoryDialog = 150;
    private int widthMarketsDialog = 755;
    private int heightMarketsDialog = 200;
    private int widthDeleteIndicatorDialog = 450; 
    private int heightDeleteIndicatorDialog = 105;  
    private static int marketId = 0;

    /**
     * Creates new form ManageUser
     */
    public ManageMarketsUi() {
        initComponents();
        //Load role names
        /*manageUser.loadUserRoles(cboAddUserUserRole, cboEditUserUserRole);
        //Load languages
        manageUser.loadLanguages(cboAddCommodityUnit, cboEditUserWorkingLanguage);*/
        //Load all markets 
        manageMarkets.loadMarkets(tblManageMarketsAllMarkets, tbmMarkets);
        //Load all districts 
        manageMarkets.loadDistricts(cboAddMarketDistrict);
        manageMarkets.loadDistricts(cboEditMarketDistrict);        
        //Load all field analysts
        manageMarkets.loadFieldAnalysts(cboAddMarketFieldAnalyst);
        manageMarkets.loadFieldAnalysts(cboEditMarketFieldAnalyst);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgAddNewMarket = new javax.swing.JDialog();
        pnlManageMarketsAddNewMarketMain = new javax.swing.JPanel();
        pnlManageMarketsAddMarketMiddle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboAddMarketDistrict = new javax.swing.JComboBox();
        cboAddMarketFieldAnalyst = new javax.swing.JComboBox();
        txtAddMarketName = new javax.swing.JTextField();
        btnAddMarketAddFieldAnalyst = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rbtAddMarketMainMarket = new javax.swing.JRadioButton();
        rbtAddMarketSlims = new javax.swing.JRadioButton();
        pnlManageMarketsAddMarketBottom = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));
        btnManageMarketsAddNewMarket = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 32767));
        btnManageMarketCancel = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));
        pnlManageMarketsAddMarketTop = new javax.swing.JPanel();
        lblManageMarketsTitle = new javax.swing.JLabel();
        dlgAddMarketFieldAnalyst = new javax.swing.JDialog();
        pnlAddFieldAnalystMain = new javax.swing.JPanel();
        txtAddFieldAnalystName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnAddFieldAnalystSave = new javax.swing.JButton();
        btnAddFieldAnalystCancel = new javax.swing.JButton();
        dlgDeleteMarket = new javax.swing.JDialog();
        pnlDeleteIndicatorMain = new javax.swing.JPanel();
        btnDeleteMarketDelete = new javax.swing.JButton();
        btnDeleteMarketCancel = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txtDeleteMarketName = new javax.swing.JTextField();
        btgAddMarketMarketType = new javax.swing.ButtonGroup();
        btnSaveEditedMarket = new javax.swing.JButton();
        dlgEditMarket = new javax.swing.JDialog();
        pnlManageMarketsAddNewMarketMain1 = new javax.swing.JPanel();
        pnlManageMarketsAddMarketMiddle1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboEditMarketDistrict = new javax.swing.JComboBox();
        cboEditMarketFieldAnalyst = new javax.swing.JComboBox();
        txtEditMarketName = new javax.swing.JTextField();
        btnEditMarketAddFieldAnalyst = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rbtEditMarketMainMarket = new javax.swing.JRadioButton();
        rbtEditMarketSlims = new javax.swing.JRadioButton();
        pnlManageMarketsAddMarketBottom1 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));
        btnManageMarketsEditNewMarket = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 32767));
        btnManageEditMarketCancel = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));
        pnlManageMarketsAddMarketTop1 = new javax.swing.JPanel();
        lblManageMarketsTitle1 = new javax.swing.JLabel();
        btgEditMarket = new javax.swing.ButtonGroup();
        pnlManageMarketsMain = new javax.swing.JPanel();
        pnlManageMarketsTop = new javax.swing.JPanel();
        btnManageMarketsAddMarket = new javax.swing.JButton();
        btnManageMArketsEditMarket = new javax.swing.JButton();
        btnManageMarketsDeleteMarket = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageMarketsAllMarkets = new javax.swing.JTable();

        dlgAddNewMarket.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgAddNewMarket.setModal(true);
        dlgAddNewMarket.setResizable(false);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel2.setText("Market Name");

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel5.setText("Market Type");

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel6.setText("District");

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel1.setText("Field Analyst");

        cboAddMarketDistrict.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        cboAddMarketFieldAnalyst.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        txtAddMarketName.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        btnAddMarketAddFieldAnalyst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Add_16x16.png"))); // NOI18N
        btnAddMarketAddFieldAnalyst.setText("Add...");
        btnAddMarketAddFieldAnalyst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMarketAddFieldAnalystActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("*");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("*");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("*");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setText("*");

        btgAddMarketMarketType.add(rbtAddMarketMainMarket);
        rbtAddMarketMainMarket.setText("Main market");

        btgAddMarketMarketType.add(rbtAddMarketSlims);
        rbtAddMarketSlims.setText("SLIMS");

        javax.swing.GroupLayout pnlManageMarketsAddMarketMiddleLayout = new javax.swing.GroupLayout(pnlManageMarketsAddMarketMiddle);
        pnlManageMarketsAddMarketMiddle.setLayout(pnlManageMarketsAddMarketMiddleLayout);
        pnlManageMarketsAddMarketMiddleLayout.setHorizontalGroup(
            pnlManageMarketsAddMarketMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageMarketsAddMarketMiddleLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlManageMarketsAddMarketMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlManageMarketsAddMarketMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboAddMarketDistrict, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddMarketName, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlManageMarketsAddMarketMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManageMarketsAddMarketMiddleLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(pnlManageMarketsAddMarketMiddleLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlManageMarketsAddMarketMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManageMarketsAddMarketMiddleLayout.createSequentialGroup()
                        .addComponent(cboAddMarketFieldAnalyst, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddMarketAddFieldAnalyst))
                    .addGroup(pnlManageMarketsAddMarketMiddleLayout.createSequentialGroup()
                        .addComponent(rbtAddMarketMainMarket)
                        .addGap(10, 10, 10)
                        .addComponent(rbtAddMarketSlims)))
                .addGroup(pnlManageMarketsAddMarketMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlManageMarketsAddMarketMiddleLayout.setVerticalGroup(
            pnlManageMarketsAddMarketMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageMarketsAddMarketMiddleLayout.createSequentialGroup()
                .addGroup(pnlManageMarketsAddMarketMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManageMarketsAddMarketMiddleLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlManageMarketsAddMarketMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddMarketName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13)
                            .addComponent(cboAddMarketFieldAnalyst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnAddMarketAddFieldAnalyst))
                        .addGap(18, 18, 18)
                        .addGroup(pnlManageMarketsAddMarketMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlManageMarketsAddMarketMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboAddMarketDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGroup(pnlManageMarketsAddMarketMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jLabel5)
                                .addComponent(jLabel16)
                                .addComponent(rbtAddMarketMainMarket)
                                .addComponent(rbtAddMarketSlims))))
                    .addGroup(pnlManageMarketsAddMarketMiddleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlManageMarketsAddMarketBottom.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlManageMarketsAddMarketBottom.setLayout(new java.awt.GridLayout(1, 0));
        pnlManageMarketsAddMarketBottom.add(filler2);

        btnManageMarketsAddNewMarket.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnManageMarketsAddNewMarket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Save_16x16.png"))); // NOI18N
        btnManageMarketsAddNewMarket.setMnemonic('N');
        btnManageMarketsAddNewMarket.setText("Save");
        btnManageMarketsAddNewMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMarketsAddNewMarketActionPerformed(evt);
            }
        });
        pnlManageMarketsAddMarketBottom.add(btnManageMarketsAddNewMarket);
        pnlManageMarketsAddMarketBottom.add(filler1);

        btnManageMarketCancel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnManageMarketCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Cancel_16x16.png"))); // NOI18N
        btnManageMarketCancel.setMnemonic('C');
        btnManageMarketCancel.setText("Cancel");
        btnManageMarketCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMarketCancelActionPerformed(evt);
            }
        });
        pnlManageMarketsAddMarketBottom.add(btnManageMarketCancel);
        pnlManageMarketsAddMarketBottom.add(filler3);

        lblManageMarketsTitle.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        lblManageMarketsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageMarketsTitle.setText("Add Market");

        javax.swing.GroupLayout pnlManageMarketsAddMarketTopLayout = new javax.swing.GroupLayout(pnlManageMarketsAddMarketTop);
        pnlManageMarketsAddMarketTop.setLayout(pnlManageMarketsAddMarketTopLayout);
        pnlManageMarketsAddMarketTopLayout.setHorizontalGroup(
            pnlManageMarketsAddMarketTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageMarketsAddMarketTopLayout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addComponent(lblManageMarketsTitle)
                .addGap(284, 284, 284))
        );
        pnlManageMarketsAddMarketTopLayout.setVerticalGroup(
            pnlManageMarketsAddMarketTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageMarketsAddMarketTopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblManageMarketsTitle))
        );

        javax.swing.GroupLayout pnlManageMarketsAddNewMarketMainLayout = new javax.swing.GroupLayout(pnlManageMarketsAddNewMarketMain);
        pnlManageMarketsAddNewMarketMain.setLayout(pnlManageMarketsAddNewMarketMainLayout);
        pnlManageMarketsAddNewMarketMainLayout.setHorizontalGroup(
            pnlManageMarketsAddNewMarketMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageMarketsAddMarketTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlManageMarketsAddMarketMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlManageMarketsAddMarketBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlManageMarketsAddNewMarketMainLayout.setVerticalGroup(
            pnlManageMarketsAddNewMarketMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageMarketsAddNewMarketMainLayout.createSequentialGroup()
                .addComponent(pnlManageMarketsAddMarketTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlManageMarketsAddMarketMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlManageMarketsAddMarketBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout dlgAddNewMarketLayout = new javax.swing.GroupLayout(dlgAddNewMarket.getContentPane());
        dlgAddNewMarket.getContentPane().setLayout(dlgAddNewMarketLayout);
        dlgAddNewMarketLayout.setHorizontalGroup(
            dlgAddNewMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageMarketsAddNewMarketMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgAddNewMarketLayout.setVerticalGroup(
            dlgAddNewMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageMarketsAddNewMarketMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dlgAddMarketFieldAnalyst.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgAddMarketFieldAnalyst.setTitle("Add New Indicator Category");
        dlgAddMarketFieldAnalyst.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dlgAddMarketFieldAnalyst.setResizable(false);

        jLabel19.setText("Field Analyst Name");

        btnAddFieldAnalystSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Save_16x16.png"))); // NOI18N
        btnAddFieldAnalystSave.setMnemonic('S');
        btnAddFieldAnalystSave.setText("Save");
        btnAddFieldAnalystSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFieldAnalystSaveActionPerformed(evt);
            }
        });

        btnAddFieldAnalystCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Cancel_16x16.png"))); // NOI18N
        btnAddFieldAnalystCancel.setMnemonic('C');
        btnAddFieldAnalystCancel.setText("Cancel");
        btnAddFieldAnalystCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFieldAnalystCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddFieldAnalystMainLayout = new javax.swing.GroupLayout(pnlAddFieldAnalystMain);
        pnlAddFieldAnalystMain.setLayout(pnlAddFieldAnalystMainLayout);
        pnlAddFieldAnalystMainLayout.setHorizontalGroup(
            pnlAddFieldAnalystMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddFieldAnalystMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddFieldAnalystMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddFieldAnalystMainLayout.createSequentialGroup()
                        .addComponent(btnAddFieldAnalystSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddFieldAnalystCancel)
                        .addContainerGap(133, Short.MAX_VALUE))
                    .addGroup(pnlAddFieldAnalystMainLayout.createSequentialGroup()
                        .addComponent(txtAddFieldAnalystName)
                        .addGap(39, 39, 39))))
        );

        pnlAddFieldAnalystMainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddFieldAnalystCancel, btnAddFieldAnalystSave});

        pnlAddFieldAnalystMainLayout.setVerticalGroup(
            pnlAddFieldAnalystMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddFieldAnalystMainLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlAddFieldAnalystMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddFieldAnalystName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(pnlAddFieldAnalystMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddFieldAnalystSave)
                    .addComponent(btnAddFieldAnalystCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAddFieldAnalystMainLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddFieldAnalystCancel, btnAddFieldAnalystSave});

        javax.swing.GroupLayout dlgAddMarketFieldAnalystLayout = new javax.swing.GroupLayout(dlgAddMarketFieldAnalyst.getContentPane());
        dlgAddMarketFieldAnalyst.getContentPane().setLayout(dlgAddMarketFieldAnalystLayout);
        dlgAddMarketFieldAnalystLayout.setHorizontalGroup(
            dlgAddMarketFieldAnalystLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddFieldAnalystMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgAddMarketFieldAnalystLayout.setVerticalGroup(
            dlgAddMarketFieldAnalystLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddFieldAnalystMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dlgDeleteMarket.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgDeleteMarket.setTitle("Delete Indicator");
        dlgDeleteMarket.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dlgDeleteMarket.setResizable(false);

        btnDeleteMarketDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Delete_16x16.png"))); // NOI18N
        btnDeleteMarketDelete.setMnemonic('R');
        btnDeleteMarketDelete.setText("Delete Market");
        btnDeleteMarketDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMarketDeleteActionPerformed(evt);
            }
        });

        btnDeleteMarketCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Cancel_16x16.png"))); // NOI18N
        btnDeleteMarketCancel.setMnemonic('C');
        btnDeleteMarketCancel.setText("Cancel");
        btnDeleteMarketCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMarketCancelActionPerformed(evt);
            }
        });

        jLabel28.setText("Market Name");

        txtDeleteMarketName.setEditable(false);

        javax.swing.GroupLayout pnlDeleteIndicatorMainLayout = new javax.swing.GroupLayout(pnlDeleteIndicatorMain);
        pnlDeleteIndicatorMain.setLayout(pnlDeleteIndicatorMainLayout);
        pnlDeleteIndicatorMainLayout.setHorizontalGroup(
            pnlDeleteIndicatorMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDeleteIndicatorMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDeleteIndicatorMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeleteIndicatorMainLayout.createSequentialGroup()
                        .addComponent(btnDeleteMarketDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteMarketCancel))
                    .addComponent(txtDeleteMarketName, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlDeleteIndicatorMainLayout.setVerticalGroup(
            pnlDeleteIndicatorMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteIndicatorMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDeleteIndicatorMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtDeleteMarketName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDeleteIndicatorMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteMarketDelete)
                    .addComponent(btnDeleteMarketCancel))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout dlgDeleteMarketLayout = new javax.swing.GroupLayout(dlgDeleteMarket.getContentPane());
        dlgDeleteMarket.getContentPane().setLayout(dlgDeleteMarketLayout);
        dlgDeleteMarketLayout.setHorizontalGroup(
            dlgDeleteMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDeleteIndicatorMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dlgDeleteMarketLayout.setVerticalGroup(
            dlgDeleteMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDeleteIndicatorMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnSaveEditedMarket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Save_16x16.png"))); // NOI18N
        btnSaveEditedMarket.setText("Save");

        dlgEditMarket.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgEditMarket.setModal(true);
        dlgEditMarket.setResizable(false);

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel3.setText("Market Name");

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel7.setText("Market Type");

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel8.setText("District");

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel4.setText("Field Analyst");

        cboEditMarketDistrict.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        cboEditMarketFieldAnalyst.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        txtEditMarketName.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        btnEditMarketAddFieldAnalyst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Add_16x16.png"))); // NOI18N
        btnEditMarketAddFieldAnalyst.setText("Add...");
        btnEditMarketAddFieldAnalyst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMarketAddFieldAnalystActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 51, 51));
        jLabel17.setText("*");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setText("*");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setText("*");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 51, 51));
        jLabel21.setText("*");

        btgEditMarket.add(rbtEditMarketMainMarket);
        rbtEditMarketMainMarket.setText("Main market");
        rbtEditMarketMainMarket.setToolTipText("");

        btgEditMarket.add(rbtEditMarketSlims);
        rbtEditMarketSlims.setText("SLIMS");
        rbtEditMarketSlims.setToolTipText("");

        javax.swing.GroupLayout pnlManageMarketsAddMarketMiddle1Layout = new javax.swing.GroupLayout(pnlManageMarketsAddMarketMiddle1);
        pnlManageMarketsAddMarketMiddle1.setLayout(pnlManageMarketsAddMarketMiddle1Layout);
        pnlManageMarketsAddMarketMiddle1Layout.setHorizontalGroup(
            pnlManageMarketsAddMarketMiddle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboEditMarketDistrict, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEditMarketName, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createSequentialGroup()
                        .addComponent(cboEditMarketFieldAnalyst, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditMarketAddFieldAnalyst))
                    .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createSequentialGroup()
                        .addComponent(rbtEditMarketMainMarket)
                        .addGap(10, 10, 10)
                        .addComponent(rbtEditMarketSlims)))
                .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlManageMarketsAddMarketMiddle1Layout.setVerticalGroup(
            pnlManageMarketsAddMarketMiddle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createSequentialGroup()
                .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditMarketName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel17)
                            .addComponent(cboEditMarketFieldAnalyst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btnEditMarketAddFieldAnalyst))
                        .addGap(18, 18, 18)
                        .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboEditMarketDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jLabel7)
                                .addComponent(jLabel21)
                                .addComponent(rbtEditMarketMainMarket)
                                .addComponent(rbtEditMarketSlims))))
                    .addGroup(pnlManageMarketsAddMarketMiddle1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlManageMarketsAddMarketBottom1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlManageMarketsAddMarketBottom1.setLayout(new java.awt.GridLayout());
        pnlManageMarketsAddMarketBottom1.add(filler4);

        btnManageMarketsEditNewMarket.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnManageMarketsEditNewMarket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Save_16x16.png"))); // NOI18N
        btnManageMarketsEditNewMarket.setMnemonic('N');
        btnManageMarketsEditNewMarket.setText("Save");
        btnManageMarketsEditNewMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMarketsEditNewMarketActionPerformed(evt);
            }
        });
        pnlManageMarketsAddMarketBottom1.add(btnManageMarketsEditNewMarket);
        pnlManageMarketsAddMarketBottom1.add(filler5);

        btnManageEditMarketCancel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnManageEditMarketCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Cancel_16x16.png"))); // NOI18N
        btnManageEditMarketCancel.setMnemonic('C');
        btnManageEditMarketCancel.setText("Cancel");
        btnManageEditMarketCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEditMarketCancelActionPerformed(evt);
            }
        });
        pnlManageMarketsAddMarketBottom1.add(btnManageEditMarketCancel);
        pnlManageMarketsAddMarketBottom1.add(filler6);

        lblManageMarketsTitle1.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        lblManageMarketsTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageMarketsTitle1.setText("Edit Market");

        javax.swing.GroupLayout pnlManageMarketsAddMarketTop1Layout = new javax.swing.GroupLayout(pnlManageMarketsAddMarketTop1);
        pnlManageMarketsAddMarketTop1.setLayout(pnlManageMarketsAddMarketTop1Layout);
        pnlManageMarketsAddMarketTop1Layout.setHorizontalGroup(
            pnlManageMarketsAddMarketTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageMarketsAddMarketTop1Layout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addComponent(lblManageMarketsTitle1)
                .addGap(284, 284, 284))
        );
        pnlManageMarketsAddMarketTop1Layout.setVerticalGroup(
            pnlManageMarketsAddMarketTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageMarketsAddMarketTop1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblManageMarketsTitle1))
        );

        javax.swing.GroupLayout pnlManageMarketsAddNewMarketMain1Layout = new javax.swing.GroupLayout(pnlManageMarketsAddNewMarketMain1);
        pnlManageMarketsAddNewMarketMain1.setLayout(pnlManageMarketsAddNewMarketMain1Layout);
        pnlManageMarketsAddNewMarketMain1Layout.setHorizontalGroup(
            pnlManageMarketsAddNewMarketMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageMarketsAddMarketTop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlManageMarketsAddMarketMiddle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlManageMarketsAddMarketBottom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlManageMarketsAddNewMarketMain1Layout.setVerticalGroup(
            pnlManageMarketsAddNewMarketMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageMarketsAddNewMarketMain1Layout.createSequentialGroup()
                .addComponent(pnlManageMarketsAddMarketTop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlManageMarketsAddMarketMiddle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlManageMarketsAddMarketBottom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout dlgEditMarketLayout = new javax.swing.GroupLayout(dlgEditMarket.getContentPane());
        dlgEditMarket.getContentPane().setLayout(dlgEditMarketLayout);
        dlgEditMarketLayout.setHorizontalGroup(
            dlgEditMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageMarketsAddNewMarketMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgEditMarketLayout.setVerticalGroup(
            dlgEditMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageMarketsAddNewMarketMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnManageMarketsAddMarket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Add_16x16.png"))); // NOI18N
        btnManageMarketsAddMarket.setMnemonic('A');
        btnManageMarketsAddMarket.setText("Add Market");
        btnManageMarketsAddMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMarketsAddMarketActionPerformed(evt);
            }
        });

        btnManageMArketsEditMarket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Edit_16x16.png"))); // NOI18N
        btnManageMArketsEditMarket.setMnemonic('E');
        btnManageMArketsEditMarket.setText("Edit Market");
        btnManageMArketsEditMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMArketsEditMarketActionPerformed(evt);
            }
        });

        btnManageMarketsDeleteMarket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/orpik/images/Delete_16x16.png"))); // NOI18N
        btnManageMarketsDeleteMarket.setMnemonic('D');
        btnManageMarketsDeleteMarket.setText("Delete Market");
        btnManageMarketsDeleteMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMarketsDeleteMarketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlManageMarketsTopLayout = new javax.swing.GroupLayout(pnlManageMarketsTop);
        pnlManageMarketsTop.setLayout(pnlManageMarketsTopLayout);
        pnlManageMarketsTopLayout.setHorizontalGroup(
            pnlManageMarketsTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageMarketsTopLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnManageMarketsAddMarket)
                .addGap(18, 18, 18)
                .addComponent(btnManageMArketsEditMarket)
                .addGap(18, 18, 18)
                .addComponent(btnManageMarketsDeleteMarket)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        pnlManageMarketsTopLayout.setVerticalGroup(
            pnlManageMarketsTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageMarketsTopLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnlManageMarketsTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageMarketsAddMarket)
                    .addComponent(btnManageMArketsEditMarket)
                    .addComponent(btnManageMarketsDeleteMarket))
                .addContainerGap())
        );

        tblManageMarketsAllMarkets.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        tblManageMarketsAllMarkets.setModel(tbmMarkets);
        tblManageMarketsAllMarkets.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblManageMarketsAllMarkets.setGridColor(new java.awt.Color(0, 51, 255));
        tblManageMarketsAllMarkets.setRowHeight(25);
        tblManageMarketsAllMarkets.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblManageMarketsAllMarkets);

        javax.swing.GroupLayout pnlManageMarketsMainLayout = new javax.swing.GroupLayout(pnlManageMarketsMain);
        pnlManageMarketsMain.setLayout(pnlManageMarketsMainLayout);
        pnlManageMarketsMainLayout.setHorizontalGroup(
            pnlManageMarketsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageMarketsTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        pnlManageMarketsMainLayout.setVerticalGroup(
            pnlManageMarketsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageMarketsMainLayout.createSequentialGroup()
                .addComponent(pnlManageMarketsTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageMarketsMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManageMarketsMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageMarketsAddMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMarketsAddMarketActionPerformed
        //Set dialog title to Add
        lblManageMarketsTitle.setText("Add Market");
        // Set add market dialog size
        dlgAddNewMarket.setSize(widthMarketsDialog, heightMarketsDialog);
        // Set add market dialog location
        dlgAddNewMarket.setLocationRelativeTo(null);
        //Clear all components 
        manageMarkets.clearComponents(txtAddMarketName, cboAddMarketDistrict, cboAddMarketFieldAnalyst, 
                rbtAddMarketMainMarket, rbtAddMarketSlims);
        // Launch add market dialog
        dlgAddNewMarket.setVisible(true);
        //Set default button
    }//GEN-LAST:event_btnManageMarketsAddMarketActionPerformed

    private void btnManageMarketsAddNewMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMarketsAddNewMarketActionPerformed
        int result = 0;
        int districtId = 0;
        int fieldAnalystId = 0;
        int marketTypeId= 0;
        String marketName = "";
        String districtName = "";
        String fieldAnalystName = "";

        //Get values
        marketName = txtAddMarketName.getText();
        districtName = cboAddMarketDistrict.getSelectedItem().toString();
        fieldAnalystName = cboAddMarketFieldAnalyst.getSelectedItem().toString();
        marketTypeId = getMarketTypeId(rbtAddMarketMainMarket, rbtAddMarketSlims);
        fieldAnalystId = fieldAnalyst.getFieldAnalystId(fieldAnalystName);
        districtId = district.getDistrictId(districtName);
        
        //Check market id
            result = manageMarkets.insertMarket(marketName, fieldAnalystId, districtId, marketTypeId);
            if(result > 0){                             
                JOptionPane.showMessageDialog(null, "Market added successfully", "Add Market",
                    JOptionPane.INFORMATION_MESSAGE);                 
            }else{
                JOptionPane.showMessageDialog(null, "Market was not added. Please try again", "Add Market",
                    JOptionPane.WARNING_MESSAGE); 
            }
    }//GEN-LAST:event_btnManageMarketsAddNewMarketActionPerformed

    private void btnManageMarketCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMarketCancelActionPerformed
        // Dispose dialog
        dlgAddNewMarket.dispose();
    }//GEN-LAST:event_btnManageMarketCancelActionPerformed

    private void btnAddMarketAddFieldAnalystActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMarketAddFieldAnalystActionPerformed
        // Launch dialog
        manageMarkets.launchDialog(dlgAddMarketFieldAnalyst, widthIndicatorCategoryDialog, heightIndicatorCategoryDialog);
    }//GEN-LAST:event_btnAddMarketAddFieldAnalystActionPerformed

    private void btnDeleteMarketDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMarketDeleteActionPerformed
        // Delete market
        int result = 0;
        int marketId = 0;

        marketId = manageMarkets.getMarketId(tblManageMarketsAllMarkets);
        result = manageMarkets.deleteMarket(marketId);
        if (result > 0) {
            //Load all markets 
            manageMarkets.loadMarkets(tblManageMarketsAllMarkets, tbmMarkets);
            JOptionPane.showMessageDialog(null, "Indicator deleted successfully", "Delete Indicator",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Deleting indicator not successful", "Delete Indicator",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteMarketDeleteActionPerformed

    private void btnDeleteMarketCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMarketCancelActionPerformed
        // Dispose delete user dialog
        dlgDeleteMarket.dispose();
    }//GEN-LAST:event_btnDeleteMarketCancelActionPerformed

    private void btnManageMarketsDeleteMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMarketsDeleteMarketActionPerformed
        // Delete market        
        int marketId = 0;
        int selectedRow = 0;
        String marketName = "";

        selectedRow = tblManageMarketsAllMarkets.getSelectedRow();
        //Check if user has selected a row
        if (selectedRow > -1) {
            //Get market id
            marketId = manageMarkets.getMarketId(tblManageMarketsAllMarkets);
            marketName = tblManageMarketsAllMarkets.getValueAt(selectedRow, 1).toString();
            txtDeleteMarketName.setText(marketName);
            
            //Launch dialog
            manageMarkets.launchDialog(dlgDeleteMarket, widthDeleteIndicatorDialog, heightDeleteIndicatorDialog);
        } else {
            //No row is selected
            JOptionPane.showMessageDialog(null, "Select market row whose market you wish to delete", "Delete Market",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnManageMarketsDeleteMarketActionPerformed

    private void btnManageMArketsEditMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMArketsEditMarketActionPerformed
        // Launch edit markets dialog
        /*int marketId = 0;
        
        //Check whether user selected a row
        if (tblManageMarketsAllMarkets.getSelectedRow() > -1) {
            //Get market id
            marketId = manageMarkets.getMarketId(tblManageMarketsAllMarkets);

            //Populate all other market details
            manageMarkets.loadMarkets(marketId, txtAddMarketName, cboAddMarketFieldAnalyst, cboAddMarketDistrict, 
                    rbtAddMarketMainMarket, rbtAddMarketSlims);   
            // Launch edit market
            lblManageMarketsTitle.setText("Edit Market");
            manageMarkets.launchDialog(dlgAddNewMarket, widthMarketsDialog, heightMarketsDialog);  
            
        } else {
            //No row was selected
            JOptionPane.showMessageDialog(null, "Select market row to edit market details", "Edit Market",
                    JOptionPane.INFORMATION_MESSAGE);
        }   */
        
        marketId = 0;
        
        //Check whether user selected a row
        if (tblManageMarketsAllMarkets.getSelectedRow() > -1) {
            //Get market id
            marketId = manageMarkets.getMarketId(tblManageMarketsAllMarkets);

            //Populate all other market details
            manageMarkets.loadMarkets(marketId, txtEditMarketName, cboEditMarketFieldAnalyst, cboEditMarketDistrict, 
                    rbtEditMarketMainMarket, rbtEditMarketSlims);   
            // Launch edit market
            //lblManageMarketsTitle.setText("Edit Market");
            manageMarkets.launchDialog(dlgEditMarket, widthMarketsDialog, heightMarketsDialog);  
            
        } else {
            //No row was selected
            JOptionPane.showMessageDialog(null, "Select market row to edit market details", "Edit Market",
                    JOptionPane.INFORMATION_MESSAGE);
        }          
    }//GEN-LAST:event_btnManageMArketsEditMarketActionPerformed

    private void btnAddFieldAnalystCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFieldAnalystCancelActionPerformed
        // Dispose indicator category dialog
        dlgAddMarketFieldAnalyst.dispose();
    }//GEN-LAST:event_btnAddFieldAnalystCancelActionPerformed

    private void btnAddFieldAnalystSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFieldAnalystSaveActionPerformed
        // Add indicator category
        int result = 0;
        int staffId = 0;
        String staffName = "";
        
        staffName = txtAddFieldAnalystName.getText();
        result = manageMarkets.addStaff(staffName);
        
        
        
        if (result > 0) {
            staffId = manageMarkets.getStaffId(staffName);
            result = manageMarkets.addFieldAnalyst(staffId);
            if(result > 0){
            JOptionPane.showMessageDialog(null, "Field analyst added successfully", "Add Field Analyst",
                    JOptionPane.INFORMATION_MESSAGE); 
            //Add field analyst to combo box
            cboAddMarketFieldAnalyst.addItem(staffName);
            //Set field analyst as selected item
            cboAddMarketFieldAnalyst.setSelectedItem(txtAddFieldAnalystName.getText());            
            }else{
            JOptionPane.showMessageDialog(null, "Field analyst not added."
                    + "\nPlease seek assistance from system administrator",
                    "Add Field Analyst",
                    JOptionPane.WARNING_MESSAGE);                
            }
        } else {
            JOptionPane.showMessageDialog(null, "staff not added."
                    + "\nPlease seek assistance from system administrator",
                    "Add Staff",
                    JOptionPane.WARNING_MESSAGE); 
        }
    }//GEN-LAST:event_btnAddFieldAnalystSaveActionPerformed

    private void btnEditMarketAddFieldAnalystActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMarketAddFieldAnalystActionPerformed
        // Launch dialog
        manageMarkets.launchDialog(dlgAddMarketFieldAnalyst, widthIndicatorCategoryDialog, heightIndicatorCategoryDialog);
    }//GEN-LAST:event_btnEditMarketAddFieldAnalystActionPerformed

    private void btnManageMarketsEditNewMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMarketsEditNewMarketActionPerformed
        int result = 0;
        int districtId = 0;
        int fieldAnalystId = 0;
        int marketTypeId = 0;
        int marketId = 0;
        String marketName = "";
        String districtName = ""; 
        String fieldAnalystName = "";
        //marketId = this.marketId;
        //Get values
        marketName = txtEditMarketName.getText();
        districtName = cboEditMarketDistrict.getSelectedItem().toString();
        fieldAnalystName = cboEditMarketFieldAnalyst.getSelectedItem().toString();
        marketTypeId = getMarketTypeId(rbtEditMarketMainMarket, rbtEditMarketSlims);
        fieldAnalystId = fieldAnalyst.getFieldAnalystId(fieldAnalystName);
        districtId = district.getDistrictId(districtName);
        
        //Check market id
            result = manageMarkets.updateMarket(marketName, fieldAnalystId, districtId, marketTypeId,ManageMarketsUi.marketId);
            if(result > 0){
                JOptionPane.showMessageDialog(null, "Market edited successfully", "Edit Market",
                    JOptionPane.INFORMATION_MESSAGE); 
            }else{
                JOptionPane.showMessageDialog(null, "Market was not edited. No changes made to market", "Edit Market",
                    JOptionPane.WARNING_MESSAGE); 
            }
    }//GEN-LAST:event_btnManageMarketsEditNewMarketActionPerformed

    private void btnManageEditMarketCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEditMarketCancelActionPerformed
        // Dispose dialog
        dlgEditMarket.dispose();
    }//GEN-LAST:event_btnManageEditMarketCancelActionPerformed

    //Get market type id
    private int getMarketTypeId(JRadioButton rbtMainMarket, JRadioButton rbtSlims){
        int marketTypeId = 0;
        try{
            if(rbtMainMarket.isSelected()){
                marketTypeId = 1;
            }else if(rbtSlims.isSelected()){
                marketTypeId = 2;
            }
        }catch(Exception exception){}
     return marketTypeId;  
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgAddMarketMarketType;
    private javax.swing.ButtonGroup btgEditMarket;
    private javax.swing.JButton btnAddFieldAnalystCancel;
    private javax.swing.JButton btnAddFieldAnalystSave;
    private javax.swing.JButton btnAddMarketAddFieldAnalyst;
    private javax.swing.JButton btnDeleteMarketCancel;
    private javax.swing.JButton btnDeleteMarketDelete;
    private javax.swing.JButton btnEditMarketAddFieldAnalyst;
    private javax.swing.JButton btnManageEditMarketCancel;
    private javax.swing.JButton btnManageMArketsEditMarket;
    private javax.swing.JButton btnManageMarketCancel;
    private javax.swing.JButton btnManageMarketsAddMarket;
    private javax.swing.JButton btnManageMarketsAddNewMarket;
    private javax.swing.JButton btnManageMarketsDeleteMarket;
    private javax.swing.JButton btnManageMarketsEditNewMarket;
    private javax.swing.JButton btnSaveEditedMarket;
    private javax.swing.JComboBox cboAddMarketDistrict;
    private javax.swing.JComboBox cboAddMarketFieldAnalyst;
    private javax.swing.JComboBox cboEditMarketDistrict;
    private javax.swing.JComboBox cboEditMarketFieldAnalyst;
    private javax.swing.JDialog dlgAddMarketFieldAnalyst;
    private javax.swing.JDialog dlgAddNewMarket;
    private javax.swing.JDialog dlgDeleteMarket;
    private javax.swing.JDialog dlgEditMarket;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManageMarketsTitle;
    private javax.swing.JLabel lblManageMarketsTitle1;
    private javax.swing.JPanel pnlAddFieldAnalystMain;
    private javax.swing.JPanel pnlDeleteIndicatorMain;
    private javax.swing.JPanel pnlManageMarketsAddMarketBottom;
    private javax.swing.JPanel pnlManageMarketsAddMarketBottom1;
    private javax.swing.JPanel pnlManageMarketsAddMarketMiddle;
    private javax.swing.JPanel pnlManageMarketsAddMarketMiddle1;
    private javax.swing.JPanel pnlManageMarketsAddMarketTop;
    private javax.swing.JPanel pnlManageMarketsAddMarketTop1;
    private javax.swing.JPanel pnlManageMarketsAddNewMarketMain;
    private javax.swing.JPanel pnlManageMarketsAddNewMarketMain1;
    public javax.swing.JPanel pnlManageMarketsMain;
    private javax.swing.JPanel pnlManageMarketsTop;
    private javax.swing.JRadioButton rbtAddMarketMainMarket;
    private javax.swing.JRadioButton rbtAddMarketSlims;
    private javax.swing.JRadioButton rbtEditMarketMainMarket;
    private javax.swing.JRadioButton rbtEditMarketSlims;
    private javax.swing.JTable tblManageMarketsAllMarkets;
    private javax.swing.JTextField txtAddFieldAnalystName;
    private javax.swing.JTextField txtAddMarketName;
    private javax.swing.JTextField txtDeleteMarketName;
    private javax.swing.JTextField txtEditMarketName;
    // End of variables declaration//GEN-END:variables
}
