/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package org.orpik.ui;

import javax.swing.JDialog;
import org.orpik.settings.global.GuiManager;

/**
 *
 * @author chemweno
 */
public class ResetPassword extends javax.swing.JDialog {

    private GuiManager guiManager = new GuiManager();
    private int width = 453;
    private int height = 246;

    /**
     * Creates new form ResetPassword
     */
    public ResetPassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Set resizeability
        this.setResizable(false);
        //Set default close operation
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //Set diaolog size
        guiManager.setDialogSize(this, width, height);
        //Center dialog on screen
        guiManager.centerDialog(this, width, height);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlResetPasswordMain = new javax.swing.JPanel();
        pnlResetPasswordTop = new javax.swing.JPanel();
        pnlResetPasswordBottom = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pwdResetPasswordRetype = new javax.swing.JPasswordField();
        pwdResetPassword = new javax.swing.JPasswordField();
        txtResetPassword = new javax.swing.JTextField();
        btnResetPasswordReset = new javax.swing.JButton();
        btnResetPasswordCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout pnlResetPasswordTopLayout = new javax.swing.GroupLayout(pnlResetPasswordTop);
        pnlResetPasswordTop.setLayout(pnlResetPasswordTopLayout);
        pnlResetPasswordTopLayout.setHorizontalGroup(
            pnlResetPasswordTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlResetPasswordTopLayout.setVerticalGroup(
            pnlResetPasswordTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        pnlResetPasswordBottom.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel1.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 52, 0, 0);
        pnlResetPasswordBottom.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel2.setText("Re-type Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlResetPasswordBottom.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel3.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 56, 0, 0);
        pnlResetPasswordBottom.add(jLabel3, gridBagConstraints);

        pwdResetPasswordRetype.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 217;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 4, 0, 116);
        pnlResetPasswordBottom.add(pwdResetPasswordRetype, gridBagConstraints);

        pwdResetPassword.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 217;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 0, 116);
        pnlResetPasswordBottom.add(pwdResetPassword, gridBagConstraints);

        txtResetPassword.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        txtResetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtResetPasswordMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 217;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 0, 116);
        pnlResetPasswordBottom.add(txtResetPassword, gridBagConstraints);

        btnResetPasswordReset.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnResetPasswordReset.setMnemonic('R');
        btnResetPasswordReset.setText("Reset");
        btnResetPasswordReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPasswordResetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 40, 22, 0);
        pnlResetPasswordBottom.add(btnResetPasswordReset, gridBagConstraints);

        btnResetPasswordCancel.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnResetPasswordCancel.setMnemonic('C');
        btnResetPasswordCancel.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 22, 0);
        pnlResetPasswordBottom.add(btnResetPasswordCancel, gridBagConstraints);

        javax.swing.GroupLayout pnlResetPasswordMainLayout = new javax.swing.GroupLayout(pnlResetPasswordMain);
        pnlResetPasswordMain.setLayout(pnlResetPasswordMainLayout);
        pnlResetPasswordMainLayout.setHorizontalGroup(
            pnlResetPasswordMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlResetPasswordTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlResetPasswordBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlResetPasswordMainLayout.setVerticalGroup(
            pnlResetPasswordMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResetPasswordMainLayout.createSequentialGroup()
                .addComponent(pnlResetPasswordTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResetPasswordBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlResetPasswordMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlResetPasswordMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtResetPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResetPasswordMouseExited
    }//GEN-LAST:event_txtResetPasswordMouseExited

    private void btnResetPasswordResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswordResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetPasswordResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ResetPassword dialog = new ResetPassword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResetPasswordCancel;
    private javax.swing.JButton btnResetPasswordReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlResetPasswordBottom;
    private javax.swing.JPanel pnlResetPasswordMain;
    private javax.swing.JPanel pnlResetPasswordTop;
    private javax.swing.JPasswordField pwdResetPassword;
    private javax.swing.JPasswordField pwdResetPasswordRetype;
    private javax.swing.JTextField txtResetPassword;
    // End of variables declaration//GEN-END:variables
}
